### ISSUE TITLE
NoWarn 444 breaks compilation with mono>3

### ISSUE THREAD

**Issue by mschubert** [IronLanguages/main#115]
In the file Solutions/Common.proj, line 162:

    <NoWarn>1591;1584;1574;444;1685;1573</NoWarn>

Warning 444 seems to be removed with mono>3, which triggers a "`444' is not a valid warning number" warning that is translated into an error as it is not in \<WarningsNotAsErrors>

Possible solutions: remove 444 from \<NoWarn> or add the corresponding validity warning to \<WarningsNotAsErrors>

**Comment by slide** [comment]
I don't see this with Mono JIT compiler version 4.2.1 (Stable 4.2.1.102/6dd2d0d Thu Nov 12 09:52:44 UTC 2015)

Is it still an issue for you?

**Comment by mschubert** [comment]
Confirmed to no longer be an issue with:

Mono JIT compiler version 4.2.2 (Stable 4.2.2.10/7b87787 Mon Dec 21 19:36:52 UTC 2015)
