### ISSUE TITLE
Module 'posixpath' not available from Release build

### ISSUE THREAD

**Issue by egarson** [IronLanguages/main#1156]
Hello

Thank you for IronPython, I'm really enjoying it.

I have an issue running the Debug versus Release configurations for ipy.exe on Mono (3.12.0) on Ubuntu (14.04). I built both Debug and Release configs the same way as per the instructions on the wiki, for example Release was built simply like so:

```bash
$ xbuild /p:Configuration=Release Solutions/IronPython.sln
```
I get an error when I try to use the Release version, while the Debug version works. Notice the ImportError below, which is odd given only a difference when building:

```bash
➜  IronLanguages git:(ipy-2.7-maint) mono bin/Debug/ipy.exe                      15-01-16 /opt/IronLanguages
IronPython 2.7.6a0 DEBUG (2.7.6.0) on Mono 4.0.30319.17020 (32-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()
➜  IronLanguages git:(ipy-2.7-maint) mono bin/Release/ipy.exe                    15-01-16 /opt/IronLanguages
Traceback (most recent call last):
  File "/opt/IronLanguages/bin/Release/Lib/site.py", line 62, in <module>
  File "/opt/IronLanguages/bin/Release/Lib/os.py", line 49, in <module>
ImportError: No module named posixpath
IronPython 2.7.6a0 (2.7.6.0) on Mono 4.0.30319.17020 (32-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
What am I doing wrong?

Thank you

**Comment by jdhardy** [comment]
Rule of thumb: if it doesn't work on Mono, it's probably our bug. :) In this case, in Debug mode there's an extra entry on `sys.path` to look in the horribly-named `External.LCA_RESTRICTED` directory for the IronPython library. Release builds expects it to be under `Lib` next to `ipy.exe` (so `bin/Release/Lib` in this case) but it's not copied there during a build.

The main reason is that I didn't expect Release builds to often be run out of a build tree, only when installed. Also, the tests are hardcoded to run `bin/Debug/ipy.exe`, so there wasn't much advantage to it. There's not much advantage to Release builds anyway, so when running out of a checkout just use the Debug build.

If you want a Release build that works, you could try:

    xbuild /t:Stage /p:BaseConfiguration=Release;Mono=true /verbosity:minimal /nologo

but I've never tried it on Mono, so it may not work. If it does, look in `Stage/Release` for the result. It's exactly how the .zip packages are built.

Also: there is a Makefile now, so you should be able to just run `make` and have a Debug build.

**Comment by egarson** [comment]
Thank you so much for your comprehensive and speedy response. I tried your suggested invocation and the net result is basically the same. (I was only hoping to build a release version to speed up invocation of unit tests, so not a huge issue).

The release build profile emits a spurious error about a license file not being present, but the file exists. Launching still complains about the posixpath module. I haven't had time to look into the error, but I may have the chance early next week. 

Kind regards,

Edward

**Comment by michaelblyons** [comment]
@egarson Did you look at the `posixpath` module shenanigans?

**Comment by egarson** [comment]
I'm afraid not, and we've changed directions so no longer using IronPython....

**Comment by felixonmars** [comment]
I got the same error when using the later suggested build command:

```
Errors:

/home/felix/projects/ironpython/src/main-ipy-2.7.5/Build.proj (Stage) ->
(Stage target) ->
/home/felix/projects/ironpython/src/main-ipy-2.7.5/Solutions/Build.IronPython.proj (Stage) ->
(Stage target) ->

        /home/felix/projects/ironpython/src/main-ipy-2.7.5/Solutions/Build.IronPython.proj: error : Cannot copy /home/felix/projects/ironpython/src/main-ipy-2.7.5/Languages/IronPython/Public/License.rtf to /home/felix/projects/ironpython/src/main-ipy-2.7.5/Stage/Release/IronPython-2.7.5/License.rtf, as the source file doesn't exist.

         23 Warning(s)
         1 Error(s)
```

The file is named `License.Rtf` instead of `License.rtf`, so I have renamed it. Then I got several missing objects related to Silverlight:

```
Errors:

/home/felix/projects/ironpython/src/main-ipy-2.7.5/Build.proj (Stage) ->
(Stage target) ->
/home/felix/projects/ironpython/src/main-ipy-2.7.5/Solutions/Build.IronPython.proj (Stage) ->
(Stage target) ->

        /home/felix/projects/ironpython/src/main-ipy-2.7.5/Solutions/Build.IronPython.proj: error : Cannot copy /home/felix/projects/ironpython/src/main-ipy-2.7.5/bin/Silverlight5Release/Microsoft.Dynamic.dll to /home/felix/projects/ironpython/src/main-ipy-2.7.5/Stage/Release/IronPython-2.7.5/Silverlight/bin/Microsoft.Dynamic.dll, as the source file doesn't exist.
        /home/felix/projects/ironpython/src/main-ipy-2.7.5/Solutions/Build.IronPython.proj: error : Cannot copy /home/felix/projects/ironpython/src/main-ipy-2.7.5/bin/Silverlight5Release/Microsoft.Dynamic.xml to /home/felix/projects/ironpython/src/main-ipy-2.7.5/Stage/Release/IronPython-2.7.5/Silverlight/bin/Microsoft.Dynamic.xml, as the source file doesn't exist.
        /home/felix/projects/ironpython/src/main-ipy-2.7.5/Solutions/Build.IronPython.proj: error : Cannot copy /home/felix/projects/ironpython/src/main-ipy-2.7.5/bin/Silverlight5Release/Microsoft.Scripting.dll to /home/felix/projects/ironpython/src/main-ipy-2.7.5/Stage/Release/IronPython-2.7.5/Silverlight/bin/Microsoft.Scripting.dll, as the source file doesn't exist.
        /home/felix/projects/ironpython/src/main-ipy-2.7.5/Solutions/Build.IronPython.proj: error : Cannot copy /home/felix/projects/ironpython/src/main-ipy-2.7.5/bin/Silverlight5Release/Microsoft.Scripting.xml to /home/felix/projects/ironpython/src/main-ipy-2.7.5/Stage/Release/IronPython-2.7.5/Silverlight/bin/Microsoft.Scripting.xml, as the source file doesn't exist.

         23 Warning(s)
         4 Error(s)
```

**Comment by chris-hawley** [comment]
any luck on fixing this?

**Comment by felixonmars** [comment]
Since there was no feedback from upstream for half a year already, I went on and managed to build it successfully by mocking the missing files and remove the related platforms afterwards.

Here is my full build script (PKGBUILD for Arch Linux), hope it is useful: https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD

**Comment by aarzee** [comment]
Any progress on this? Tried building on OS X 10.11 with Mono installed, build log is [here](https://ghostbin.com/paste/ey9oa), this is what happens when I run the interpreter:

```
carloss-mbp:main-ipy-2.7.5 aarzee$ mono bin/Release/ipy.exe
Traceback (most recent call last):
  File "/Users/aarzee/main-ipy-2.7.5/bin/Release/Lib/site.py", line 62, in <module>
  File "/Users/aarzee/main-ipy-2.7.5/bin/Release/Lib/os.py", line 49, in <module>
ImportError: No module named posixpath
IronPython 2.7.5 (2.7.5.0) on Mono 4.0.30319.17020 (64-bit)
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/aarzee/main-ipy-2.7.5/bin/Release/Lib/os.py", line 49, in <module>
ImportError: No module named posixpath

>>>             
```

**Comment by slide** [comment]
There best option for running a release build from the tree is to export IRONPYTHONPATH to point to the Lib directory under the External. LCA_ Restricted/IronPython/27. Then you can run the interpreter from the build tree in Release mode.
