### ISSUE TITLE
Inappropriate exceptions thrown in certain situations when running in a restricted AppDomain

### ISSUE THREAD

**Issue by DavidKDeutsch** [IronLanguages/main#1157]
Given the following code:

```C#
class Program
	{
		static void Main(string[] args)
		{
			var engine = CreateEngine();
			
			
			string goodScript = "invalid()";
			string badScript = @"
def func():
	invalid()
func()";

			string badScript2 = "def func:";

			engine.Execute(goodScript);
		}

		private static ScriptEngine CreateEngine()
		{
			PermissionSet permSet = new PermissionSet(PermissionState.None);
			permSet.AddPermission(new SecurityPermission(SecurityPermissionFlag.Execution));
			permSet.AddPermission(new ReflectionPermission(PermissionState.Unrestricted));
			AppDomainSetup adSetup = new AppDomainSetup();
			adSetup.ApplicationBase = Environment.CurrentDirectory;
			StrongName fullTrustAssembly = typeof(Program).Assembly.Evidence.GetHostEvidence<StrongName>();
			var domain = AppDomain.CreateDomain("IronPythonSandbox", null, adSetup, permSet, fullTrustAssembly);
			return Python.CreateEngine(domain);
		}
	}
```
When I execute `goodScript` I get a proper exception describing the fact that "invalid" is not defined. However, when I run `badScript`, I get an `ArgumentNullException` (thrown by `System.Reflection.RuntimeMethodInfo.MakeGenericMethod`).  This is very odd, as the only difference is that the latter string calls the invalid method from a Python function.

In addition, when I execute `badScript2`, I get a `SecurityException` instead of proper exception describing the syntax error.

All three scripts work fine (i.e., throw appropriate exceptions) if I am not running the engine in a restricted AppDomain.

**Comment by jdhardy** [comment]
I think the issue is the exception objects not getting serialized across the domain boundary properly, although I can't quite figure out why (AppDomains seem to confuse the heck out of the debugger).

**Comment by DavidKDeutsch** [comment]
After some judicious googling, I found a solution whereby the exception itself does not need to be serialized:

```c#
var source = engine.CreateScriptSourceFromString(badScript);
ObjectHandle exceptionHandle = null;
var o = source.ExecuteAndWrap(out exceptionHandle);
var exceptionOperations = engine.GetService<ExceptionOperations>();
var s = exceptionOperations.FormatException(exceptionHandle);
```
