### ISSUE TITLE
Is IronRuby still under active development?

### ISSUE THREAD

**Issue by jdantonio** [IronLanguages/main#1160]
The last release of IronRuby was in March of 2011. Much has happened to Ruby and its ecosystem since then. Is IronRuby still being actively developed?

**Comment by slide** [comment]
There are a couple of people that have made pull requests and things have been merged in, but I don't think there is much active development going on.

**Comment by jdantonio** [comment]
@slide Thanks for the quick response. That's unfortunate, but knowing certainly helps.
