### ISSUE TITLE
anydbm/whichdb bug when inserting non-str keys

### ISSUE THREAD

**Issue by irmen** [IronLanguages/main#1165]
whichdb seems to get confused if you use a non-str key in a db opened by anydbm.
whichdb.whichdb() returns None in that case.
It should return dumbdbm, which it does just fine if you only use str keys.

Because of this, anydbm.open() crashes when you try to reopen a previously created dbm file.

code to reproduce this bug:

```
import anydbm
import whichdb

key = u"key\u20ac".encode("utf-8")     # if you make this a normal str, everything works fine

db=anydbm.open("test.dbm", "c")
db[key]="value"
db.close()
del db

print "whichdb:", whichdb.whichdb("test.dbm")

db=anydbm.open("test.dbm")
print "value:", db[key]
```

the above code works fine on python 2.7 but prints "whichdb: None" and then crashes, when you run it with ironpython 2.7

**Comment by slide** [comment]
This is because dumbdbm.py uses **repr** which adds the u in front of the string since all strings are unicode in IronPython. I'll see what workaround I can come up with.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#119
