### ISSUE TITLE
`__eq__` of OrderedDict subclasses does not have precedence when comparing with OrderedDicts

### ISSUE THREAD

**Issue by pekkaklarck** [IronLanguages/main#1168]
First of all, is this the correct place to submit IronPython bugs or should I still use the tracker at http://ironpython.codeplex.com/? There aforementioned page has a note that source is here on GitHub but doesn't tell anything about issue tracker.

---

Running this code on CPython succeeds but with IronPython the second assert fails:

``` python
from collections import OrderedDict

class Example(OrderedDict):

    def __eq__(self, other):
        return True

e = Example()
o = OrderedDict(a=1)

assert e == o, 'e != o'
assert o == e, 'o != e'
```

Because `Example` is a subclass of `OrderedDict`, its `__eq__` should be used in both of the above comparisons.

Interestingly this version with `int` works correctly:

``` python
class Example(int):

    def __eq__(self, other):
        return True

e = Example()
o = 42

assert e == o, 'e != o'
assert o == e, 'o != e'
```

**Comment by paweljasinski** [comment]
This is the right location, codeplex is no longer used.

**Comment by pekkaklarck** [comment]
Ok, good to know that you have moved to GitHub for good. You might want to make that a bit more clear on the old CodePlex site, though, and perhaps mention it also at http://ironpython.net/.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#34
