### ISSUE TITLE
IronPython not compatible?

### ISSUE THREAD

**Issue by Dado87** [IronLanguages/main#1172]
Hi everyone,

I have an issue with running of some code in IronPyrhon (actually in GHPython script Editor, which uses IronPython). I want to run some structural engineering software (Strand7) externaly with the help of API of this software. If I run it in Python IDLE it works well, but inside Iron I get some error. Please also look at the .pdf file attached here: http://www.grasshopper3d.com/forum/topics/problem-with-api-in-ghpython

Do somebody know what's wrong? Any sugestions? Thanks for the answears!

Regards,
Damir

**Comment by paweljasinski** [comment]
I believe when you running idle, you are using a cpython not an ironpython. From information captured in pdf, I suspect you have found a ctype incompatibility between cpython and ironpython, which is a valid bug. What could help us is a test case which does not have dependencies on external library (Strand7) or detailed instructions how to reproduce a problem.

**Comment by slide** [comment]
Incomplete. Reopen with more information.
