### ISSUE TITLE
Crash while attempting to create a ThreadPool from a Thread

### ISSUE THREAD

**Issue by malcomdw** [IronLanguages/main#1180]
There was a bug in the python libraries which leads to crash while creating a ThreadPool from a Thread. This bug was reported to Python guys and fixed [here](http://bugs.python.org/issue14881), however, it is not applied in the python libraries shipped with IronPython.

I don't know the Python updating cycle followed here in IronPython but, would it be possible just to apply [this](https://hg.python.org/cpython/rev/1f5d2642929a) changeset in the current Python libraries bundled in IronPhyton? I can make a pull request if needed.

Regards.

**Comment by paweljasinski** [comment]
Yes, please make a pull request.
In 2.7 line of Ironpython, the libraries are updated conservatively, only when needed. In 3.x line, Jeff aims to do regular syncs with cpython.

**Comment by malcomdw** [comment]
Thanks.
Closing this due pull request.
