### ISSUE TITLE
datetime.strptime with timezone broken in IronPython 2.7.5

### ISSUE THREAD

**Issue by akarppinen** [IronLanguages/main#1186]
In 2.7.4:

C:\Users\Administrator>ipy
IronPython 2.7.4 (2.7.0.40) on .NET 4.0.30319.17929 (32-bit)
Type "help", "copyright", "credits" or "license" for more information.
from datetime import datetime
data='2015-03-19T16:00:35+02:00'
fmt='%Y-%m-%dT%H:%M:%S%z'
datetime.strptime(data, fmt)
datetime.datetime(2015, 3, 19, 16, 0, 35)

Same in 2.7.5:

C:\Users\karppan>ipy
IronPython 2.7.5 (2.7.5.0) on .NET 4.0.30319.34209 (32-bit)
Type "help", "copyright", "credits" or "license" for more information.
from datetime import datetime
data='2015-03-19T16:00:35+02:00'
fmt='%Y-%m-%dT%H:%M:%S%z'
datetime.strptime(data, fmt)
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ValueError: time data does not match format
data=2015-03-19T16:00:35+02:00, fmt=%Y-%m-%dT%H:%M:%S%z, to: yyyy'-'M'-'d'T'H':'m':'ss''

**Comment by paweljasinski** [comment]
Things are a bit complicated. The only platform where given example works is IronPython 2.7.4. Any other implementation of python I tried, either:
* complains about ```ValueError: 'z' is a bad directive in format '%Y-%m-%dT%H:%M:%S%z'``` (2.7 cpython linux, cpython windows)

or

* errors with ```ValueError: time data '2015-03-19T16:00:35+02:00' does not match format '%Y-%m-%dT%H:%M:%S%z'``` (3.4 cpython linux)

In the first case, %z is not universally supported on all platforms http://bugs.python.org/issue6641
In the second case timezone string contains extra `:` in `+02:00` which should be `+0200` according to python documentation. https://docs.python.org/2/library/datetime.html#strftime-and-strptime-behavior

The remaining question, why did it work in 2.7.4? IronPython version of datetime.strptime used to have a catch all clause, which was flagged as a bug: https://ironpython.codeplex.com/workitem/30047

Ideally fix for `%z` would match behaviour of on the platform where it is supported (cpython 3x). I don't think going back to 2.7.4 "tolerant" mode is an option.

In your case, as a workaround I would try to call .net `DateTime.Parse` directly.

**Comment by slozier** [comment]
Here's the fixed up test code (had to remove the colon in the utc offset), this one works in CPython 3.5 but fails in CPython 2.7.

```
from datetime import datetime
data='2015-03-19T16:00:35+0200'
fmt='%Y-%m-%dT%H:%M:%S%z'
datetime.strptime(data, fmt)
```

We should be getting the following error message:

```
ValueError: 'z' is a bad directive in format '%Y-%m-%dT%H:%M:%S%z'
```

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#118
