### ISSUE TITLE
IronPython fails a simple code on new Mono - find a test case

### ISSUE THREAD

**Issue by PiotrZierhoffer** [IronLanguages/main#1188]
It is not an IronPython issue, to be sure. It occurred on one of the latest mono commits. I'm writing here, because user mailing list archives look very inactive.

I have posted a mono bug here: https://bugzilla.xamarin.com/show_bug.cgi?id=28235

Microsoft.Scripting is dark magic for me, so I have created an example that fails:

```csharp
var engine = Python.CreateEngine();
var scope = engine.CreateScope();
var imports = engine.CreateScriptSourceFromString("import clr\n"
   +"clr.AddReference('System.Drawing')"); //System.Drawing is just an example
imports.Execute(scope);//this works
var error = engine.CreateScriptSourceFromString ("import System.Drawing");
error.Execute (scope); //EXCEPTION HERE
```

The exception I get is `System.MissingMemberException: 'NullImporter' object has no attribute 'find_module'`

As said before, it works on .NET and Mono prior to 5ecee9a0c835bb4a5f6f2723bc4d6af9a42da70d

Would anyone be kind enough to help me find a simple test case that would show the problem without referencing IronPython, Microsoft.Scripting, etc?

For the greater glory of both IronPython and Mono :+1:

**Comment by slide** [comment]
The mailing list is active. Please use it for questions.

**Comment by PiotrZierhoffer** [comment]
I  wondered how it happened - when I have checked last time, the last post was from 2011. Magic. My apologies then.

**Comment by slide** [comment]
Make sure you are using this mailing list:
https://mail.python.org/mailman/listinfo/ironpython-users

**Comment by PiotrZierhoffer** [comment]
As a final note, Mono team managed to fix the bug without further help, so the case is invalid either way.
