### ISSUE TITLE
Breaking changes in DLR without version bump

### ISSUE THREAD

**Issue by sopelt** [IronLanguages/main#1194]
Creating an `IronPython 2.7.5` engine fails on systems with "old" `Microsoft.Dynamic` DLLs.
Example code

    IronPython.Hosting.Python.CreateEngine();

fails with

    Method not found: 'System.Collections.Generic.IEnumerable`1<!!0> Microsoft.Scripting.Utils.ReflectionUtils.GetCustomAttributes(System.Reflection.Assembly, Boolean)'.

on systems having `IronPython 2.7.3` installed.

This seems to be caused by breaking changes ([see this commit](https://github.com/IronLanguages/main/commit/5277117fb4c1b31535ba51dcf6e1799aece3debd/Runtime/Microsoft.Dynamic/Utils/ReflectionUtils.cs)) in `Microsoft.Dynamic` while keeping the `AssemblyVersion` at `1.1.0.20`.

Both `Microsoft.Dynamic` assemblies (from release `2.7.3` and `2.7.5`) have the signature

    Microsoft.Dynamic, Version=1.1.0.20, Culture=neutral, PublicKeyToken=7f709c5b713576e1

and if `2.7.3` is installed the "old version" is found in the GAC which breaks many development and deployment scenarios.

Looking at the full list of changes in the `Microsoft.Dynamic` API between releases `2.7.3` and `2.7.5` shows more situations the might cause issues:

    public class Microsoft.Scripting.Utils.HybridMapping<T>
        + public const int SIZE - Value: 4096
        + public int StrongAdd(T value,Int32 pos)
        - public int StrongAdd(T value)
    public class Microsoft.Scripting.Utils.ExceptionUtils
        + public static void RemoveData(Exception e,Object key)
    public class Microsoft.Scripting.Utils.ReflectionUtils
        + public static T GetCustomAttribute(Assembly assembly,Boolean inherit)
        + public static IEnumerable<T> GetCustomAttributes(Assembly assembly,Boolean inherit)
    public class Microsoft.Scripting.Utils.StringUtils
        + public static bool TryParseDateTimeExact(String s,String[] formats,IFormatProvider provider,DateTimeStyles style,out DateTime result)

Is there a reason for sticking with the same version for DLR assemblies?

**Comment by jdhardy** [comment]
The changes were not intentionally breaking; there's just no automated
process to catch issues so they slipped through.

What did you use is to generate that diff?

**Comment by sopelt** [comment]
Hey Jeff, thank you for the swift reply.

I used [ApiChange](https://apichange.codeplex.com/). It seems to work OK (but there are probably better tools ... but they are often proprietary).

Wouldn't it be easier to increment DLR versions for any IronPython-release just to be on the safe side? Or use git history to ensure that the DLR files are untouched between releases?

Do you think there will be a maintenance release/build which includes a version-bumped DLR or is this scenario too unlikely to be a common issue?

**Comment by sopelt** [comment]
(Or have DLR as a separate project/NuGet which on a second look might be what you guys are planning.)

**Comment by Gumpy** [comment]
I get this error when installing IronPython from nuget.

**Comment by petsuter** [comment]
I think I have the same problem. When 2.7.1 is installed, these assemblies are used from the GAC, even though I referenced the assemblies from the Nuget packages folder of Iron Python 2.7.5.

    System.Reflection.TargetInvocationException was unhandled
      HResult=-2146232828
      Message=Failed to load language 'IronPython 2.7.5': Method not found: 'Boolean Microsoft.Scripting.Utils.ReflectionUtils.IsInterface(System.Type)'.
      Source=Microsoft.Scripting
      StackTrace:
       at Microsoft.Scripting.Runtime.LanguageConfiguration.LoadLanguageContext(ScriptDomainManager domainManager, Boolean& alreadyLoaded)
       at Microsoft.Scripting.Runtime.DlrConfiguration.LoadLanguageContext(ScriptDomainManager manager, LanguageConfiguration config)
       at Microsoft.Scripting.Runtime.DlrConfiguration.TryLoadLanguage(ScriptDomainManager manager, AssemblyQualifiedTypeName providerName, LanguageContext& language)
       at Microsoft.Scripting.Hosting.ScriptRuntime.GetEngineByTypeName(String assemblyQualifiedTypeName)
       at IronPython.Hosting.Python.GetEngine(ScriptRuntime runtime)
       at IronPython.Hosting.Python.CreateEngine(IDictionary`2 options)
       ...
      InnerException: System.MissingMethodException
       HResult=-2146233069
       Message=Method not found: 'Boolean Microsoft.Scripting.Utils.ReflectionUtils.IsInterface(System.Type)'.
       Source=IronPython
       StackTrace:
            at IronPython.Runtime.Binding.PythonBinder.DomainManager_AssemblyLoaded(Object sender, AssemblyLoadedEventArgs e)
            at IronPython.Runtime.Binding.PythonBinder..ctor(PythonContext pythonContext, CodeContext context)
            at IronPython.Runtime.PythonContext..ctor(ScriptDomainManager manager, IDictionary`2 options)
       InnerException: 

Bumping all versions for any release sounds like the right thing to do.

**Comment by jaredbroad** [comment]
What was your fix for this issue @sopelt? Its pretty difficult to fix. I get this issue just from adding a reference to the iron python project in another project.

**Comment by sopelt** [comment]
Hey @jaredbroad, I just ensured that there are no IronPython versions (and I suspect IronRuby as well) installed on my system (i.e. `Microsoft.Dynamic` assemblies in the GAC). That obviously only works for machines under your control and might still cause issues when shipping to a client machine (or you would have to check/ensure during installation).

I hope a general fix will become available with the next IronPython release (i.e. after @jdhardy increases the DLR assembly version and ships new packages).

**Comment by jaredbroad** [comment]
Thanks @sopelt, I used `gacutil -l` to check GAC dll's and Microsoft.Dynamic wasn't in there, I actually ended up simply removing the Microsoft.* files from my *other* project, in a totally separate unrelated directory and somehow it started working again! :)

**Comment by TrexinanF14** [comment]
Hi @jdhardy, may I ask if there has been any further conversation about version bumping dlls when updates come out? We had the exact problem occur that @sopelt described, we shipped an installer that contains the microsoft.dynamic assembly, but because the installer uses the file version first to check for diffs it didn't do the replacement properly. We are trying to change our installer to just always copy the file, but it would make it more convenient if the file versions were bumped for new Ironpython releases.

**Comment by slide** [comment]
We will be bumping the DLR version on the next release of IronPython.

**Comment by slide** [comment]
The version number for 2.7.6.3 should be 1.1.1.21 for the DLR.
