### ISSUE TITLE
IronRuby - Fiber support?

### ISSUE THREAD

**Issue by avarisc** [IronLanguages/main#1195]
When attempting to create a Fiber in IronRuby, I get an undefined constant error for the name Fiber.  I've tried searching, and made sure to load the threading library in case it was in there.

I am emulating an existing engine whose scripts make use of Fiber; before resorting to trying to implement it myself, I want to be sure I'm not just missing something.

So my question is, does IronRuby support the Fiber class? (If not, if anyone happens to know of a "soft" implementation, feel free to mention it.)

EDIT - Worth noting that I've tried both the official binaries as well as building from source.

**Comment by avarisc** [comment]
I was able to find this, in case anyone else has a similar issue. Less performant, but "mostly" compatible, and meets my personal requirements: https://gist.github.com/tmm1/4631

Would still like to formally know if it is supported, planned, or not supported, as searching the topic yields very little information.

**Comment by slide** [comment]
Please open this on the ironruby repo (https://github.com/IronLanguages/ironruby)
