### ISSUE TITLE
ImportModule fails with "no module named"

### ISSUE THREAD

**Issue by dericrock** [IronLanguages/main#1197]
Using IronPython 2.7.5, I'm creating an assembly with
`"C:\Program Files (x86)\IronPython 2.7\ipy.exe" "C:\Program Files (x86)\IronPython 2.7\Tools\Scripts\pyc.py" script1.py /main:script1.py /target:dll`

I copy the file script1.dll to my C# deploy folder. In my C# code I have this:
            `ScriptEngine engine = Python.CreateEngine();`
            `ICollection<string> searchPaths = engine.GetSearchPaths();`
            `string exePath = Path.GetDirectoryName(Application.ExecutablePath);`
            `searchPaths.Add(exePath);`
            `engine.SetSearchPaths(searchPaths);`

After which this works:
            `ScriptScope scope = engine.CreateScope();`
            `engine.Execute("import clr", scope);`
            `engine.Execute("clr.AddReference(\"script1.dll\")", scope);`
            `engine.Execute("from script1 import *", scope);`

But this fails with "no module named script1" error:
            `ScriptScope scope = engine.ImportModule("script1");`

What am I missing? Is `ImportModule` meant to load an assembly without access to the .py file? Adding the file script1.py to my deploy folder makes it work. But I only want to distribute a .dll file.

**Comment by jdhardy** [comment]
I'd have to check, but I think `ImportModule` is intended to load them from source.

**Comment by slide** [comment]
I just tested this and it works just fine. I am able to import from a DLL using engine.ImportModule.
