### ISSUE TITLE
SystemError in compiler in dictionary initialization with integer tuple as a key

### ISSUE THREAD

**Issue by mkavalec** [IronLanguages/main#1207]
I came accross a compiler error when compiling the xlwt package.

The compiler fails to compile following code from BIFFRecords.py:

        valid_active_pane0 = {
                # entries are of the form:
                # (int(px > 0),int(px>0)) -> allowed values
                (0,0):(3,),
                (0,1):(2,3),
                (1,0):(1,3),
                (1,1):(0,1,2,3),
        }

with an error:

SystemError: An expression of type 'System.Int32' cannot be used to initialize an array of type 'System.Object'

The error is thrown by clr.CompileModules.

A workaround is a rewrite it using dict: 

        valid_active_pane = dict([ 
                ((0,0),(3,)),
                ((0,1),(2,3)),
                ((1,0),(1,3)),
                ((1,1),(0,1,2,3)),
        ])

The problem is with numeric tuples, e.g. (1L,1L) fails too, string tuples are OK.

**Comment by slide** [comment]
I'm pretty sure this is the same as #1444
