### ISSUE TITLE
SetTrace Memory Leak

### ISSUE THREAD

**Issue by pfay** [IronLanguages/main#1214]
Wondering was issue #963 Memory Leak ever resolved because I am experiencing a similar problem.

I am attaching a new trace delegate to multiple engines as part of a batch execution system. Each execution of an engine leaks more memory. I have taken a memory profile before and after and it would seem that the memory leak is a result of PythonTracebackListener, as per attached screen grab.

![memory leak profile](https://cloud.githubusercontent.com/assets/6431364/8303664/5181b1b6-1997-11e5-8712-cf5fc04f7aa5.PNG)

**Comment by markusschaber** [comment]
I'm the submitter of #963, and as far as I can see, it is not yet resolved.

**Comment by markusschaber** [comment]
The issue is still reproducible using 2.7.6 RC 2, when useing settrace.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#117
