### ISSUE TITLE
Random except 'fall through' in multithreaded environment. 

### ISSUE THREAD

**Issue by alexknorr** [IronLanguages/main#1217]
We have a strange problem when using separated ScriptEngine instances in a multithreaded environment using the current main trunk embedded in a heavily frequented .NET 4.0 server application. In random cases specialized python exceptions are not catched inside python when a piece of script code is executed parallel in multiple threads.

Here is a Unit Test Case:

``` csharph
using IronPython.Hosting;
using Microsoft.Scripting.Hosting;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Collections.Generic;
using System.Linq;

namespace IronPythonTests
{
    [TestClass]
    public class ParallelTest
    {
        const string RandomFallThrough =
            "a = 1\n" +
            "try:\n" +
            "   a.missing\n" +
            "except AttributeError:\n" +
            "   pass";

        const string ReliableCatch =
            "a = 1\n" +
            "try:\n" +
            "   a.missing\n" +
            "except Exception:\n" +
            "   pass";

        const int NumThreads = 10;

        [TestMethod]
        public void IsolatedEngine_RandomFallThrough()
        {
            Parallelize(() => Python.CreateEngine().Execute(RandomFallThrough));
        }

        [TestMethod]
        public void IsolatedEngine_ReliableCatch()
        {
            Parallelize(() => Python.CreateEngine().Execute(ReliableCatch));
        }

        [TestMethod]
        public void SharedEngine_RandomFallThrough()
        {
            ScriptEngine engine = Python.CreateEngine();
            Parallelize(() => engine.Execute(RandomFallThrough));
        }

        [TestMethod]
        public void SharedEngine_ReliableCatch()
        {
            ScriptEngine engine = Python.CreateEngine();
            Parallelize(() => engine.Execute(ReliableCatch));
        }

        private void Parallelize(Action action)
        {
            List<IAsyncResult> ars = new List<IAsyncResult>();

            for (int i = 0; i < NumThreads; i++)
            {
                ars.Add(action.BeginInvoke((a) => { }, null));
            }

            ars.ForEach(ar => action.EndInvoke(ar));
        }
    }
}
```

On a 8-core the fall-through (IsolatedEngine_RandomFallThrough) occurs once per 5-20 runs while an broad catch (IsolatedEngine_ReliableCatch) never seems to be ignored. I can say that the exception in this test-case is always a MissingMemberException (which maps to AttributeError).

The problem is the same with a shared engine (SharedEngine_RandomFallThrough) where one would commonly expect such effects and was first encountered by just importing the os module as there are try-except sections with AttributeError or NameError filters.

I have not much time to look into that, but will post more info when i may see something to start off. The only thing i have found is that there are some ThreadStatic marked fields spread all over the library storing context information for the interpreter an other stuff. I don't know how reliable this may be and what side effects it may trigger when a thread is rescheduled (via ThreadPool f.i.) reusing a local storage slot, but theoretically it should not be the problem if they are implemented correctly which i trust for now.

**Comment by alexknorr** [comment]
For the time i could resolve the problems with some changes provided in #1218. I don´t know how covering the solution is thought...

**Comment by slide** [comment]
This has been fixed in IronLanguages/ironpython2
