### ISSUE TITLE
TLS v 1.2

### ISSUE THREAD

**Issue by theonewolf** [IronLanguages/main#1221]
I have some servers which refuse to talk SSL to IronPython applications because IronPython has no way of using TLS v1.2:

```
2015/08/04 22:21:19 http: TLS handshake error from :41089: tls: unsupported SSLv2 handshake received
2015/08/04 22:41:12 http: TLS handshake error from :41597: tls: client offered an unsupported, maximum protocol version of 300
2015/08/04 22:41:39 http: TLS handshake error from :41605: tls: client offered an unsupported, maximum protocol version of 301
```

I am not sure how, but on my Ubuntu 14.04 LTS systems Python 2.7.6 somehow defaults to actually using TLS v 1.2.

IronPython actually starts with an SSLv2 handshake, which is not good.

**Comment by jdhardy** [comment]
I think this is the default for .NET's own SSL/TLS implementation, but we should definitely tweak it. Even better would be to implement the entire SSLContext API from 2.7.10, but that might not be possible under .NET.

**Comment by theonewolf** [comment]
Ah yes :-) 2.7.10 SSLContext API would be wonderful.

Just something to think about.  There's no easy way to get TLS 1.2 without a third-party library then right (or patching IronPython myself)?

**Comment by jdhardy** [comment]
I'd have to study the SSL.cs code to be sure but there might be a way to
tweak the settings at runtime. It will also depend on what version of .net
added 1.2 support.

**Comment by markusschaber** [comment]
http://traktorfisch.de/post/125463291329/activating-tls-11-and-12-on-sslstream-while may be helpful (Disclamer: I wrote it a few days ago because I needed it for C# coding)

**Comment by rassilon** [comment]
A complete SSLContext API seems unlikely given how little SslStream supports, it does seem feasible to change the default SSL protocol to more closely match >= 2.7.9 behavior so that pypi won't complain.

In fact, here's probably the absolutely bare minimum first stab for enough TLSv1, etc.. to make pip happy talking to pypi.python.org. 

https://github.com/rassilon/main/commit/a4c0c5abc3598ff0c881846764fc8592cad5ac8e

Thoughts?

**Comment by jdhardy** [comment]
@rassilon LGTM. Can you send it as a PR?

**Comment by rassilon** [comment]
@jdhardy , done.
