### ISSUE TITLE
Andrew Carmichael

### ISSUE THREAD

**Issue by ancatge** [IronLanguages/main#1223]
Ive recently downloaded Iron Python to try it out. 
The following fails:-

import sys
sys.path.append(r'C:\Program Files (x86)\IronPython 2.7\Lib')
import clr

....................................NameError: name 'clr' is not defined

Not a good start. Where do I get clr from?

**Comment by slide** [comment]
Please use the mailing list for questions. https://mail.python.org/mailman/listinfo/ironpython-users

**Comment by ancatge** [comment]
Apologies Alex, still finding my feet with this site and app. Anyway seems Ive solved the issue.
Cheers

Andy
