### ISSUE TITLE
ZipFile provides no mechanism for closing the underlying file object

### ISSUE THREAD

**Issue by dxtodorovic** [IronLanguages/main#1224]
When using ZipFile.extractall() method to unpack nested zip files, file operations on underlying files sometimes (almost always) throw an error "The file is used by another process". It appears it has to do with file handles on underlying files not being closed in timely manner (possibly related to issue: [1047](https://github.com/IronLanguages/main/issues/1047)).

Similar bug was documented in CPython (http://bugs.python.org/issue9846) and was closed with a proposed fix ([issue9846.diff](http://bugs.python.org/file19778/issue9846.diff)). Upon applying said fix, the issue no longer appeared to happen.

**Comment by slide** [comment]
That CPython issue says it was NOT backported to 2.7 though. I would think we would want to maintain the same (even broken) behavior as CPython in case some code is working around this somehow.

**Comment by slide** [comment]
Nevermind, later in the thread it is indeed backported.
