### ISSUE TITLE
Linq not working under Windows 10

### ISSUE THREAD

**Issue by arnoldpistorius** [IronLanguages/main#1229]
```
clr.ImportExtensions(System.Linq)
```

does not work under Windows 10

Trace:

```
Traceback (most recent call last):
  File "Foo.py", line 2, in <module>
AttributeError: 'namespace#' object attribute 'Linq' is read-only
```

**Comment by jdhardy** [comment]
What do you use for `clr.AddReference`? I believe some of the assembly
names may have changed in .NET 4.6.

**Comment by arnoldpistorius** [comment]
Yes I became aware the System.Core needs to be referenced. My scripts are working again :)
