### ISSUE TITLE
Crash when using `docutils.core.publish_doctree`

### ISSUE THREAD

**Issue by pekkaklarck** [IronLanguages/main#1230]
I'm trying to use `docutils` with IronPython. Installation succeeded with `pip` without problems and running a sample rst file through `rst2html.py` worked fine too. However, when I try to use `publish_doctree` programmatically, the whole IronPython process crashes with a dialog saying

> IronPython console has stopped working.

and after closing it I got

> Process is terminated due to StackOverflowException.

to console. I can reliably reproduce the crash with just this code:

``` python
from docutils.core import publish_doctree
publish_doctree("hello\n-----\n")
```

This is likely related to #1040. The difference is that in my usage `rst2html.py` worked fine.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#113
