### ISSUE TITLE
IronPython and WPF only string binding

### ISSUE THREAD

**Issue by simplicbe** [IronLanguages/main#1234]
Hello,

currently i have a problem with bindings in WPF/IronPython. It seems that only binding string works correctly and random binding errors occures. Here is an article on stackoverflow with the issue: [IronPython binding works but throws binding-errors](http://stackoverflow.com/questions/32891160/ironpython-binding-works-but-throws-binding-errors)

Another curious thing is, that when opening WPF Windows which uses binding, getter get called much more often as using plane c# code. This makes large WPF user interfaces very slow. If the UI contains some `DataGrid`s, it is not usable any more.

Where can i start debugging this behaviour, or does already a solution exists?

Thank you very much!

**Comment by simplicbe** [comment]
Starting at `MetaPythonObject` does not seems to be correct. No other tips for starting to research? But i thought that all python objects are basing on this class, so why does the getter/setter not get called when using WPF? Thank you.

**Comment by jdhardy** [comment]
`MetaPythonObject` is involved, but debugging IDMOP classes can be a bit tricky. Combining that with WPF bindings and I'm not really sure where to begin either. Wish I could be more help.

**Comment by simplicbe** [comment]
Maybe i found some thing else, which has to do with this issue. When i attach the debugger to the application, and activate that exceptions are displayed where they are thrown, i get this additional exception:

![ip_runtimeexception](https://cloud.githubusercontent.com/assets/14359329/11401349/785244e8-9392-11e5-92eb-e595b81d516b.png)

IronPython is search for the `__dict__` attribute in a c# base class, which is implemented in all ironpython view models. But it does not found `__dict__`. The exception it self is cached in ironpython, so the application does no throw any exception.

Or am i totally wrong?

**Comment by simplicbe** [comment]
Related to #1232 and will be solved there.
