### ISSUE TITLE
how to use IronPython to debug the Script whit some breakpoints step by step ?

### ISSUE THREAD

**Issue by heyxEvget** [IronLanguages/main#1239]
Hi, I am a fresh man on IronPython in C# Code,I want to create a Python Script Compiler depending on IronPython. I wish the Compiler just have a simple method to insert breakpoints and debugging them. Could you please give me some help. And I upload My project [there](https://github.com/heyxEvget/IronPython-Debugger)

**Comment by simplicbe** [comment]
For debugging IronPython you can use [Python Tools for Visual Studio](http://microsoft.github.io/PTVS/) or just use the pdb / bdb module which is shipped together with python.

**Comment by heyxEvget** [comment]
hi simplicbe,
    thanks for your help, but is there any to debug the Python Script in my own Project ? I have already post [there](https://github.com/heyxEvget/IronPython-Debugger).I want to create a IDE for scripting Python code.

**Comment by simplicbe** [comment]
In this case you have to go a little bit deeper. Take a look at the dynamic debugging possibilities: [Debugging IronPython scripts in hosted (embedded) environment](http://stackoverflow.com/questions/676188/debugging-ironpython-scripts-in-hosted-embedded-environment). There are also a lot more articles on stackoverflow which will help you out.

**Comment by KeithJRome** [comment]
Look into using sys.settrace(). It allows you to instrument python code, and with a little creativity can be used to build a debugging experience within your app. https://docs.python.org/2/library/sys.html#sys.settrace

**Comment by heyxEvget** [comment]
hi simplicbe,
   I had get something useful from the page which you post to me, and I have a problem whit that how to  place the breakpoints in the script files and get hit them. could you give me some sample code,thanks.

**Comment by heyxEvget** [comment]
hi KeithJRome,
   thanks for your suggestion. I have use these code in my recent project.
    <code> _debugThread = new Thread(() =>
            {
                _debugWindow = new DebugWindow(engine);
                _debugWindow.Show();
                System.Windows.Threading.Dispatcher.Run();
            });
            _debugThread.SetApartmentState(ApartmentState.STA);
            _debugThread.Start();

            _debugWindowReady.WaitOne();
            engine.SetTrace(_debugWindow.OnTracebackReceived);
</code>
but there is a problem that I don't know how to insert some breakpoints on my script. could you please give me more help ? thanks very much !

**Comment by simplicbe** [comment]
I've created a blog entry for this. Will be published this weekend. That should solve your problem.

**Comment by maxmont** [comment]
Hi,

I try also to debug python script hosted by my app.
How can I place breakpoints?

Thanks
