### ISSUE TITLE
How to watch the variables(global and  local variable) value embedding in c# Code ?

### ISSUE THREAD

**Issue by heyxEvget** [IronLanguages/main#1242]
Hi,
    I'm using IronPython embedding  in vs2012 with c# code. and I need to watch the Var's Value when the script is debugging?  is the current Version IronPython support this ? if  it suppord ,Is there any method which I can use ?or when the IronPython can support it ?

 Could you please give me some help ? you can see my project there:[https://github.com/heyxEvget/IronPython-Debugger/tree/master/SoftWare]
I use this code:
 engine.SetTrace(OnTraceback);
 private void OnTraceback(TraceBackFrame frame, string result, object payload)
{
            switch (result)
               {
                case "call":
                    TracebackCall();
                    break;
                case "line":
                    TracebackLine();
                    break;
                case "return":
                    TracebackReturn();
                    break;
            }
}

**Comment by slide** [comment]
Please use the mailing list at https://mail.python.org/mailman/listinfo/ironpython-users for questions

**Comment by simplicbe** [comment]
You could also use stackoverflow instead.
