### ISSUE TITLE
Cannot run pip on Mono

### ISSUE THREAD

**Issue by matthewblott** [IronLanguages/main#1243]
Hi,

I've installed IronPython for mono on OSX and it seems to work without any issues. I can open a terminal using ipy and call .NET code successfully. However pip doesn't run. I get the following error when I run "ipy -X:Frames -m pip install [package name]" from the terminal:

Could not import runpy module

Any ideas?

Thanks in advance.

Matt :-)

**Comment by slide** [comment]
Sorry for the long response time, we are just getting tests up and running on mono. Our mono support should be better in the future. I'll take s look at this issue soon.

**Comment by matthewblott** [comment]
Thanks for the response. I just downloaded and built the last release (2.7.6.3) and the error was the same so I presume this is still open?

Moving forward, is Mono going to get full support or will the focus be on .NET Core? My assumption was the latter but my experience with .NET Core hasn't been good so far (it's a real moving target) in which case I'm guessing a fully supported and stable IronPython on POSIX based systems is some time away.

**Comment by slide** [comment]
We're going to support mono AND .NET Core.

**Comment by devkhan** [comment]
Getting this:

```
$ mono ./ipy64.exe -X:Frames -X:FullFrames -m ensurepip
  File "/temp/ironpython3/Src/StdLib/Lib/_collections_abc.py", line 65
    class Hashable(metaclass=ABCMeta):

                            ^
SyntaxError: unexpected token '='
Could not import runpy module
```

on `IronPython 3.0.0a0 DEBUG (3.0.0.0) on Mono 4.0.30319.42000 (32-bit)` on macOS 10.12.

**Comment by slide** [comment]
Ipy3 is in a different repo and is not currently ready for usage.

**Comment by slide** [comment]
Didn't mean to close

**Comment by cwt** [comment]
FYI: I also got this on Fedora 25, Mono JIT compiler version 4.4.2

```shell
$ mono ipyw64.exe -X:Frames -m ensurepip
Traceback (most recent call last):
  File "/home/cwt/Temp/IronPython-2.7.7/Lib/logging/__init__.py", line 861, in emit
    msg = self.format(record)
  File "/tmp/tmpborCfd/pip-8.1.1-py2.py3-none-any.whl/pip/utils/logging.py", line 108, in format
    if self.should_color():
  File "/tmp/tmpborCfd/pip-8.1.1-py2.py3-none-any.whl/pip/utils/logging.py", line 95, in should_color
    if hasattr(real_stream, "isatty") and real_stream.isatty():
SystemError: GetStdHandle
Logged from file basecommand.py, line 1

**Comment by slide** [comment]
Yeah, the isatty function currently will only work on Windows. It calls GetStdHandle via P/Invoke, which doesn't exist on non-Windows platforms.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#72
