### ISSUE TITLE
Expected int got slice, when using start index in for-loop

### ISSUE THREAD

**Issue by simplicbe** [IronLanguages/main#1251]
When i execute the current script:

```
from System.Collections.Generic import List
lst = List[str]()
lst.Add("Hello")
lst.Add("World")

for i in lst[1:]:
    print i
```

the error message `TypeError: expected int, got slice` is thrown.

If i make a python `list` out of the `lst`, every thing works:

```
for i in list(lst)[1:]:
    print i
```

I try to find the issue, but may be some one has a good idea why this behaviour is as it is.

**Comment by simplicbe** [comment]
There is one thing i do not understand, when trying find the reasong for this behaviour. When the `binder` gets created the first time, this method in PythonGetSliceBinder.cs is called: 
```
public override DynamicMetaObject Bind(DynamicMetaObject target, DynamicMetaObject[] args) {
    return PythonProtocol.Index(this, PythonIndexType.GetSlice, ArrayUtils.Insert(target, args));
}
```

So the call site binder is created for using slices. As far as i understood, this will only be done once, later the binder is cached and only `MakeSlice` gets called. Now the curious thing:

If i set a breake point to `MakeSlice`, the correct integer values will be passed, this can even be seen here (added some line for debugging):

![dybanucinstructions generated cs](https://cloud.githubusercontent.com/assets/14359329/11528495/6dc15988-98e7-11e5-8709-9362a5aa562c.png)

If i continue debugging by going to the next step (breakpoint in makeSlice in PythonOps.cs):

![makeslice](https://cloud.githubusercontent.com/assets/14359329/11528547/c8f049ae-98e7-11e5-8da0-08a1c53cf823.png)

I directly come to the method `SimpleTypeError` in BinderOps, but where is this method called inside the dlr?

Maybe some one has some information to clearify things, thank you!

**Comment by jdhardy** [comment]
Sort answer is, because it's a .NET type, IP just calls the overloaded [] indexer for List. IP does extend other types (such as String) to look like Python types (str) but that hasn't been done for List<T>/IList<T>.

As for what the DLR is doing, off the top of my head, I'm not sure. You'd have to catch when the DLR code is actually compiled; that is, when the AST is turned into interpreted code.

**Comment by simplicbe** [comment]
Thank you for that information. I will research some information in the code, maybe i get this to work. Just for trying and learning.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#109
