### ISSUE TITLE
Support importing from embedded resources

### ISSUE THREAD

**Issue by sopelt** [IronLanguages/main#1253]
Inspired by several stackoverflow questions (e.g. [this one](http://stackoverflow.com/questions/33956131/ironpython-dependencies-for-scripts-stored-as-strings)) I was wondering if supporting imports from embedded resources in a way similar to zipimport would be a reasonable request.

As discussed on stackoverflow one could implement a PlatformAdaptationLayer or an importer (path_hooks ...) to solve this issue. Given that deploying the standard libs or custom scripts as files is unwanted for some deployment scenarios embedded resources could be an interesting solution.

By adding a DLL or EXE to sys.paths and having an importer in place could probably work.

I am not sure if there are downsides to having such an importer added as a default but shipping it as an option and having some documentation/samples might be nice. (I had a very short look at zipimport and it seems to use several internal things that might be harder to accomplish externally?!)

If there is interest I could have a look at proposing an implementation.

**Comment by slide** [comment]
Sounds like something that could be really useful

**Comment by KeithJRome** [comment]
Sounds like you are looking for the meta path importer I added in 2012. As far as I know, it still works (a very large customer still uses this in a major production app, and they've not reported any problems to me).

main/Languages/IronPython/IronPython.Modules/ResourceMetaPathImporter.cs

**Comment by sopelt** [comment]
Thank you for the swift reply! ResourceMetaPathImporter looks interesting! I'll give it a try and "document" it within a stackoverflow answer given that they have quite the visibility. I thought I looked for "GetManifestResourceStream" but well... ;)

Just two quick questions @KeithJRome ... does stuff have to be zipped as well and do I have to specify a loader per assembly containing embedded resources or how does that get resolved? With path_hooks as I understand it the loader could check for *.dll and *.exe within path and add those to its resource-resolvable assemblies ...

**Comment by KeithJRome** [comment]
It uses zipimporter internally, so yes the resource needs to be zipped before compiling. It has been many years since I touched that code, and I don't have access to the source where it was being used... but I do recall that you need to instantiate an importer per module being used and add it to sys.meta_path.

**Comment by simplicbe** [comment]
I've done this a few weeks ago, this is possible with the next release. If someone need some information how to do this. please take a look here: https://github.com/simplic-systems/simplic-dlr and for more details: https://github.com/simplic-systems/simplic-dlr/blob/master/src/Simplic.Dlr/Import/GenericImporter.cs Do to this, you need the newest, self compiled version, cause I've made some changes together with Jeff for this.
