### ISSUE TITLE
Split IronRuby into its own repository

### ISSUE THREAD

**Issue by slide** [IronLanguages/main#1255]
This way if someone wants to come along and own it more, they don't have to go through IronPython folks for merge requests, etc.

**Comment by simplicbe** [comment]
Good point, why does IronRuby didn't get an own repository initially?

**Comment by slide** [comment]
It didn't because the two languages (IronPython and IronRuby) were tied to the DLR very closely.

**Comment by simplicbe** [comment]
When splitting the repository, I think we should also clean up some old stuff, like https://github.com/IronLanguages/main/tree/ipy-2.7-maint/External/Tools Or is there any reason why this is in this repository?

**Comment by slide** [comment]
@simplicbe Yes, cleanup is a good idea.
