### ISSUE TITLE
Microsoft.Scripting.Metadata is used for?

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1257]
I'm just wondering what `Microsoft.Scripting.Metadata` is used for.

As far as I can tell it's used by the `Microsoft.Scripting.Utils.ReflectionUtils.GetVisibleExtensionMethods` (in main\Runtime\Microsoft.Dynamic\Utils\ReflectionUtils.cs) which in turn is used by nothing (other than by some commented out code in main\Languages\IronPython\IronPython\Runtime\ExtensionMethodSet.cs).

Perhaps I'm missing something...

**Comment by slide** [comment]
Please use the mailing list for questions. https://mail.python.org/mailman/listinfo/ironpython-users
