### ISSUE TITLE
assert statement doesn't use monkey patched AssertionError exception

### ISSUE THREAD

**Issue by rassilon** [IronLanguages/main#1258]
The fix seems simple enough, but I'm not sure how to write the necessary C# for IronPython.

Thoughts?

Bill

**Comment by slide** [comment]
Do you have a repro?

**Comment by rassilon** [comment]
pytest once you get past making it happy enough for stdout/stderr capturing complains that it can't see the AssertionError it creates. (sadly those local changes to improve the fd <-> PythonFile mapping I have need more work :frowning: )

The cause is simple enough to find. It appears that the AssertStatement reduces directly to calling PythonOps.RaiseAssertionError. That method just doesn't lookup the current builtin dictionary content for AssertionError.

Bill

**Comment by jdhardy** [comment]
So pytest replaces the builtin AssertionError with it's own? I'm surprised
that even worked in CPython, but I guess we have to support it. You should
be able to access the builtins module from the PythonContext (somehow) and
do the lookup from there.

**Comment by rassilon** [comment]
Yeah, pytest reevaluates the sub expressions from the failed assert statement to allow one to more easily determine which sub expression is false.

**Comment by rassilon** [comment]
Well I managed to come up with something. I'm just not sure if the else or the fallback case makes sense or not: 

        public static void RaiseAssertionError(CodeContext context, object msg) {
            PythonDictionary builtins = context.GetBuiltinsDict() ?? PythonContext.GetContext(context).BuiltinModuleDict;

            object obj;
            var message = String.Empty;

            if (msg != null) {
                message = PythonOps.ToString(msg);
            }

            if (builtins._storage.TryGetValue("AssertionError", out obj)) {
                PythonType type = obj as PythonType;
                if (type != null) {
                    throw PythonOps.CreateThrowable(type, message);
                } else {
                    throw PythonOps.CreateThrowable(DynamicHelpers.GetPythonType(obj), message);
                }
            }
            throw PythonOps.AssertionError("{0}", message);
        }

The actual PR would move the logic itself into PythonOps.AssertionError.

(There's a matching change due to the prototype change to AssertStatement of course, but that's just passing in the Parent.LocalContext property into the new context argument of this function.)

Thoughts?

**Comment by rassilon** [comment]
pytest is one complex piece of Python software, btw. After this change, it now is dying inside the logic it contains to reproduce the source code based on the traceback frame objects from the Python exception information. Ugh.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#107
