### ISSUE TITLE
Tests failed to run under Mono

### ISSUE THREAD

**Issue by felixonmars** [IronLanguages/main#1259]
Most (if not all) tests fails here with mono 4.2.1.102-1. Any hints?

Logs at http://paste.ubuntu.com/13958558/ (Too long to paste here)

**Comment by paweljasinski** [comment]
tests assume to be run on windows
powershell, .bat
--pawel

**Comment by felixonmars** [comment]
Would you be interested in PR to make the tests run on Mono/Linux?

**Comment by jdhardy** [comment]
Very, but there are a lot of hardcoded Windows assumptions in the test
config, so it might not be easy. There's also a lot of tests that don't
pass even on Windows, but the "2.x" tests should all work. Still, if you
can get it to mostly work I'd very much appreciate it.

**Comment by slide** [comment]
We're working on this one right now, have a lot of tests passing, but haven't merged anything in yet.

**Comment by slide** [comment]
Lot's of the tests are now passing on Linux. I will keep this open until we have them all triaged.

**Comment by slide** [comment]
tests are passing on mono under IronLanguages/ironpython2
