### ISSUE TITLE
IronPython: Unknown warning codes break the build for Mono

### ISSUE THREAD

**Issue by marcusva** [IronLanguages/main#126]
Certain .NET warning codes, namely 444 and 0429, do not exist in the Mono 3.2.1 framework, breaking the build process for IronPython. It would be great to remove the warnings for (at least) Mono-driven builds.

The host platform for the build with those issues is FreeBSD (all currently maintained versions) with Mono 3.2.1. Other platforms using Mono are most likely affected by the problem, too.

Patches can be found at 
http://svnweb.freebsd.org/ports/head/lang/ironpython/files/patch-Languages-IronPython-IronPython-IronPython.csproj?revision=322866
and 
http://svnweb.freebsd.org/ports/head/lang/ironpython/files/patch-Solutions-Common.proj?revision=322866

**Comment by slide** [comment]
I don't see this with the latest mono (Mono JIT compiler version 4.2.1 (Stable 4.2.1.102/6dd2d0d Thu Nov 12 09:52:44 UTC 2015)) can we close this out, or is FreeBSD still back on 3.2.1?
