### ISSUE TITLE
_winreg should not present on Linux

### ISSUE THREAD

**Issue by felixonmars** [IronLanguages/main#1260]
The `_winreg` module of CPython is not present on Linux, and many code (built-in libraries as well as 3rd party libraries) depends on this behavior to determine if it's on Windows. For example, the built-in module `mimetypes` have this code path (L237 in 2.7.5 release):

```
        # Windows only
        if not _winreg:
            return
```

And _winreg being present will generate the following error when trying to initialize `mimetypes.MimeTypes`:

```
>>> import mimetypes
>>> mimetypes.MimeTypes()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/ipy/Lib/mimetypes.py", line 66, in __init__
  File "/usr/lib/ipy/Lib/mimetypes.py", line 355, in init
  File "/usr/lib/ipy/Lib/mimetypes.py", line 257, in read_windows_registry
NotImplementedError: The method or operation is not implemented.
```

An easy workaround is to override sys.modules in path.py with:

```
sys.modules["_winreg"] = None
```

So it works:

```
>>> mimetypes.MimeTypes()
<mimetypes.MimeTypes instance at 0x000000000000002B>
```

**Comment by jdhardy** [comment]
That's terrible :(.

I suppose _winreg could throw an `ImportError` in `PerformModuleReload` on
non-Windows platforms. Would be the easiest fix.

**Comment by slide** [comment]
This is fixed in my addition of "invalid platforms" for modules.
