### ISSUE TITLE
distutils.sysconfig.get_python_lib() returns wrong path for Linux

### ISSUE THREAD

**Issue by felixonmars** [IronLanguages/main#1262]
When running with Mono under Linux, the `distutils.sysconfig.get_python_lib()` method returns wrong path that doesn't exist.

My IronPython installation is under /usr/lib/ipy folder, and here is the result:

```
>>> from distutils import sysconfig
>>> sysconfig.get_python_lib(plat_specific=1, standard_lib=1)
'/usr/lib/ipy/lib/python2.7'
```

**Comment by jdhardy** [comment]
I'm not sure what the standard layout is on Unix - where should the
IronPython library be placed? As similar as possible to CPython,  but even
that varies from distro to distro I think.

**Comment by felixonmars** [comment]
The path returned is similar to CPython, but doesn't match IronPython's installation, which is using `nt` layout. I am not sure if it would be an easy fix since `os.name` currently returns `posix` under Linux/Mono, while `sys.platform` returns `cli`.

For a packager's perspective, I really hope that IronPython could be installed to Unix layout, so it's no longer an issue. However, it's a harder way as we still need to deal with other problems like the `_init_posix` function relying on Makefile, etc.

**Comment by jdhardy** [comment]
Well, it can bypass the Makefile parsing, or use a dummy Makefile, whatever
is easiest. Honestly, when I package stuff for Linux I just shove it in
/opt and be done with it. So if you can recommend something that works for
Arch and other distros it would be helpful.

**Comment by felixonmars** [comment]
Just had a look at the current layout - it's a bit harder than I thought. Current distutils (and maybe others) will think the unix layout to be something like "lib/python2.7", which will conflict with CPython if install in the same PREFIX. so keeping something like `/usr/lib/ipy-2.7/Lib` may not be the best idea, but it's not that bad either.

I may need to hack with shipped distutils and setuptools to respect the path. Currently setuptools still installs to `target/usr/lib/python2.7/site-packages`.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#105
