### ISSUE TITLE
distutils.sysconfig.get_config_vars() tries to init for posix system and fails to find Makefile

### ISSUE THREAD

**Issue by felixonmars** [IronLanguages/main#1263]
When running with Mono under Linux, the `distutils.sysconfig.get_config_vars()` method tries to run `_init_posix()` and fails due to missing Makefile.

A simple workaround in distutils/sysconfig.py (L485) could fix this:

```
func = globals().get("_init_" + os.name if sys.platform != "cli" else "nt"
```

**Comment by simplicbe** [comment]
Why do you not create a pull request for this? Than it will be reviewed and maybe merged.

**Comment by felixonmars** [comment]
It looks like a hack rather than a proper fix to me, so I thought it may be better to discuss a bit first :)

**Comment by slide** [comment]
Do you have a specific operation that you were trying to do when you ran into this? Something that would help figure out a specific use case?

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#104
