### ISSUE TITLE
how to judge the script has been executed finished which the code is embedding in c# Code ?

### ISSUE THREAD

**Issue by heyxEvget** [IronLanguages/main#1264]
hi，
    is there some flag or property to let me know the script has been executed finished in other thrend and the code is embedding in c# Code ?

**Comment by simplicbe** [comment]
I'm sure the issue section is not made for those questions. But i even did not get what you want. Script execution will block a thread until it's finished, so you could implement your own logic for that case. But without understanding your issue completly or even have some code which shows the problem, it's hard to get what you want. You may add some example code. But in general i would ask those question via Mailing-List (in this case not) or move it to stackoverflow.

**Comment by slide** [comment]
Please use the mailing list for questions. https://mail.python.org/mailman/listinfo/ironpython-users
