### ISSUE TITLE
Type information is lost during method resolution

### ISSUE THREAD

**Issue by slide** [IronLanguages/main#1267]
This was found when trying to fix #435 

```
>python2
>>> import datetime
>>> class mydate(datetime.datetime): pass
...
>>> mydate.now()
mydate(2015, 12, 21, 5, 53, 2, 797939)
>>>
```

```
>ipy
>>> import datetime
>>> class mydate(datetime.datetime): pass
...
>>> mydate.now()
datetime.datetime(2015, 12, 21, 5, 53, 2, 797939)
>>>
```

This occurs because the type information is lost by the time you get to the __repr__ method in datetime.cs. 'this" is seen as a datetime object, and nothing seems to allow you to get back to the mydate name.

**Comment by rassilon** [comment]
Isn't that what the PythonType properties from the return value from this code are for?

      DynamicHelpers.GetPythonTypeFromType(GetType())

`cPickle.FindModuleForGlobal` when given `PythonType` uses `PythonType.Get__module__` or `PythonOps.TryGetBoundAttr(context, obj, "__module__",...)`

I would hope the PythonType case would be the most common occurrence when that function is called for pickling out object instances.

**Comment by slide** [comment]
GetType() returns datetime, because that is what the method is resolved to, a member of datetime.

**Comment by rassilon** [comment]
Oh, I understand better I think. `mydate.now()` ends up calling the `datetime.now()` static method. Does PythonContext contain the current `__class__`? i.e. `mydate`

**Comment by slide** [comment]
No, I don't think it does

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#103
