### ISSUE TITLE
Wrong __eq__ is called during comparing a function-result of the class X

### ISSUE THREAD

**Issue by simplicbe** [IronLanguages/main#1268]
The following report is taken from stackoverflow, due to the fact, that the user has no github account: http://stackoverflow.com/q/34594698/2630261

I (Krid from SO) ran across a strange phenonemon with IronPython (2.7.5). Please take a look at the following example code:

```
class X(object):        
    def __eq__(self, other):
        print "__eq__"
        return False

    def foo(self):
        return 1

a = X()

print a.foo == a.foo
```

When run with IronPython the output is:

```
__eq__
False
```

I don't understand why the equality operator overload of class X is used (a.foo has type instancemethod, not X).

When using CPython the output is

```
True
```

I guess this is a bug in IronPython. 

Thank you all!

**Comment by simplicbe** [comment]
@slide or @jdhardy do you have any idea about this?

**Comment by slide** [comment]
I'll try and take a look at this soon.

**Comment by jdhardy** [comment]
It seems to only occur for bound methods, not unbound methods:

```
>>> print a.foo == a.foo
__eq__
False
>>> print a.foo
<bound method X.foo of <X object at 0x000000000000002B>>
>>> X.foo
<unbound method X.foo>
>>> print X.foo == X.foo
True
```

**Comment by jdhardy** [comment]
https://github.com/IronLanguages/main/blob/ipy-2.7-maint/Languages/IronPython/IronPython/Runtime/Method.cs#L149 is the smoking gun. It compares the instances for equality when it should probably compare for identity.

**Comment by jdhardy** [comment]
In CPython (2.7):
```
>>> a = X()
>>> a.foo == a.foo
True
>>> b = X()
>>> a.foo == b.foo
False
>>>
```

So it should be an identity match on the instance.
