### ISSUE TITLE
FinishCondition not called before GetMetaObject

### ISSUE THREAD

**Issue by karelkcg** [IronLanguages/main#1269]
I see the exception in the title. It comes and goes depending on various changes in the Python sources, so it is not easily possible to provide a concise example. It happens under both Mono and .net.

Is this something that could be triggered from userspace? If so, what might I be doing wrong? If not, is there much chance of it getting fixed without an example? Anything I can try to help diagnose the bug, please let me know. Many thanks.

**Comment by simplicbe** [comment]
From my point of view, you could point out your problem and the caused exception a little but more. For me, i don't get what you want.

**Comment by karelkcg** [comment]
> i don't get what you want.

The usual objective when reporting an apparent bug is to obtain a fix or a workaround. 

There may well be enough to go on because there is only one place in the sources where that exception could come from.  To be clear, that place is inside IronPython: https://github.com/IronLanguages/main/blob/8ea9c16cedc5df632a43130e08e3e5df8e96ec60/Languages/IronPython/IronPython/Runtime/Binding/ConditionalBuilder.cs , line 142.

While I cannot produce a small example, there may be things I can do if someone is interested in working on a fix. Maybe I can get a stacktrace, maybe I can print out the expression IPY dies on, etc. But I don't know what would help, or whether anyone wants to spend their time on this.

**Comment by jdhardy** [comment]
If you can run with -X:ExceptionDetail and -X:ShowClrExceptions that would
help.

**Comment by karelkcg** [comment]
Many thanks for the suggestion. The output is below. Anything else I can do, please let me know.

FinishCondition not called before GetMetaObject
at IronPython.Runtime.Binding.ConditionalBuilder.GetMetaObject (System.Dynamic.DynamicMetaObject[]) <0x001ef>
at IronPython.Runtime.Binding.MetaPythonType/MetaGetBinderHelper.Finish (bool) <0x0006b>
at IronPython.Runtime.Binding.MetaPythonType/GetBinderHelper`1<System.Dynamic.DynamicMetaObject>.MakeTypeGetMember () <0x00495>
at IronPython.Runtime.Binding.MetaPythonType.GetMemberWorker (System.Dynamic.DynamicMetaObjectBinder,System.Linq.Expressions.Expression) <0x00093>
at IronPython.Runtime.Binding.MetaPythonType.GetMember (IronPython.Runtime.Binding.PythonGetMemberBinder,System.Dynamic.DynamicMetaObject) <0x0002b>
at IronPython.Runtime.Binding.MetaUserObject.Fallback (System.Dynamic.DynamicMetaObjectBinder,System.Dynamic.DynamicMetaObject) <0x0016b>
at IronPython.Runtime.Binding.MetaUserObject.FallbackGetError (System.Dynamic.DynamicMetaObjectBinder,System.Dynamic.DynamicMetaObject) <0x00047>
at IronPython.Runtime.Binding.MetaUserObject/GetBinderHelper.FallbackError () <0x00023>
at IronPython.Runtime.Binding.MetaUserObject/MetaGetBinderHelper.MakeGetAttributeRule (IronPython.Runtime.Binding.MetaUserObject/GetBindingInfo,IronPython.Runtime.Types.IPythonObject,IronPython.Runtime.Types.PythonTypeSlot,System.Dynamic.DynamicMetaObject) <0x000e8>
at IronPython.Runtime.Binding.MetaUserObject/MetaGetBinderHelper.BindGetAttribute (IronPython.Runtime.Types.PythonTypeSlot) <0x0002b>
at IronPython.Runtime.Binding.MetaUserObject/GetOrInvokeBinderHelper`1<System.Dynamic.DynamicMetaObject>.Bind (IronPython.Runtime.CodeContext,string) <0x0008e>
at IronPython.Runtime.Binding.MetaUserObject.GetMemberWorker (System.Dynamic.DynamicMetaObjectBinder,System.Dynamic.DynamicMetaObject) <0x00083>
at IronPython.Runtime.Binding.MetaUserObject.GetMember (IronPython.Runtime.Binding.PythonGetMemberBinder,System.Dynamic.DynamicMetaObject) <0x00017>
at IronPython.Runtime.Binding.PythonGetMemberBinder.Bind (System.Dynamic.DynamicMetaObject,System.Dynamic.DynamicMetaObject[]) <0x00106>
at System.Dynamic.DynamicMetaObjectBinder.Bind (object[],System.Collections.ObjectModel.ReadOnlyCollection`1<System.Linq.Expressions.ParameterExpression>,System.Linq.Expressions.LabelTarget) <0x001c0>
at System.Runtime.CompilerServices.CallSiteBinder.BindCore<System.Func`4<System.Runtime.CompilerServices.CallSite, object, IronPython.Runtime.CodeContext, object>> (System.Runtime.CompilerServices.CallSite`1<System.Func`4<System.Runtime.CompilerServices.CallSite, object, IronPython.Runtime.CodeContext, object>>,object[]) <0x000a1>
at System.Dynamic.UpdateDelegates.UpdateAndExecute2<object, IronPython.Runtime.CodeContext, object> (System.Runtime.CompilerServices.CallSite,object,IronPython.Runtime.CodeContext) <0x004d3>
at IronPython.Runtime.Binding.FastGetBase.Update (System.Runtime.CompilerServices.CallSite,object,IronPython.Runtime.CodeContext) <0x00063>
at IronPython.Runtime.Types.TypeGet.TargetOptimizing (System.Runtime.CompilerServices.CallSite,object,IronPython.Runtime.CodeContext) <0x000ab>
at (wrapper dynamic-method) object.__call__$1787 (System.Runtime.CompilerServices.Closure,IronPython.Runtime.PythonFunction,object,object,object) <0x002cc>

SystemError: FinishCondition not called before GetMetaObject
CLR Exception:
    InvalidOperationException
:
FinishCondition not called before GetMetaObject

**Comment by takashioomoto** [comment]
I ran into this same bug (W7, 64-bit, VS2013 Express, IronPython 2.7.6.3). Trigger on my use case seems to be if there are several sleep/wakeup requests made to the thread where IronPython is running. At some point `MetaGetBinderHelper` methods start being called instead of `FastGetBinderHelper`. This makes it hard to make it reproducible with a snippet.

I suggest finding a situation where IronPython.Runtime.Binding.MetaPythonType.GetMemberWorker() is consistently called. The additional requirement to trigger the exception is that `MakeTypeGetMember()` will use the attribute search by `__getattr__`, as seen in this snippet:

```
if (!isFinal) {
    // the member doesn't exist anywhere in the type hierarchy, see if
    // we define __getattr__ on our meta type.
    if (metaType.TryResolveSlot(_context, "__getattr__", out pts) && 
        !pts.IsSetDescriptor(lookupContext, metaType)) { // we tried get/set descriptors initially
        AddMetaGetAttribute(metaType, pts);
        isFinal = pts.GetAlwaysSucceeds;
    }
}
(...)
return Finish(metaOnly);
```

This implementation works fine in fast binding, but fails when the meta variant is used. Reason is that the AddMetaGetAttribute provides insufficient information for the ConditionalBuilder to complete.

**Comment by kunom** [comment]
The point is that dynamic recompilation only kicks in after 100 invocations:

``` c#
        internal bool ShouldUseNonOptimizedSite {
            get {
                return _hitCount < 100;
            }
        }
```

I am working on a reproduction script and am half-way through. See below. At the moment, I can reproduce the stack trace until _IronPython.Runtime.Binding.MetaUserObject/GetOrInvokeBinderHelper`1.Bind_.

``` python
from System.Diagnostics import Debugger
Debugger.Launch()
# ---
class Meta(type):
    def __new__(mcs, name, bases, dict):
        return type.__new__(mcs, name, bases, dict)

class A():
    __metaclass__ = Meta
    def b(self):
        return 4
# ---
from System.CodeDom.Compiler import CompilerParameters
from Microsoft.CSharp import CSharpCodeProvider

params = CompilerParameters()
params.GenerateInMemory = True
params.ReferencedAssemblies.Add('System.Core.dll')
params.ReferencedAssemblies.Add('Microsoft.CSharp.dll')

results = CSharpCodeProvider({"CompilerVersion": "v4.0"}).CompileAssemblyFromSource(params,  """
namespace Foo
{
    public static class Bar
    {
        public static void RunFunc(dynamic obj) { obj(); }
    }
}""")
for e in results.Errors:
    print(e)
assert not results.Errors.HasErrors

import clr
clr.AddReference(results.CompiledAssembly)

from Foo import Bar
# ---
a = A()
for i in range(200):
    print(i)
    Bar.RunFunc(a.b)
```

**Comment by takashioomoto** [comment]
Thank you for the quick response!

I can't run the repro right now, so I'm not sure how much the following helps...
Target application uses Scapy lib, and this is part of base_classes.py:

```
class Packet_metaclass(type):
    def __new__(cls, name, bases, dct):
        if "fields_desc" in dct: # perform resolution of references to other packets
            current_fld = dct["fields_desc"]
            resolved_fld = []
            for f in current_fld:
                if isinstance(f, Packet_metaclass): # reference to another fields_desc
                    for f2 in f.fields_desc:
                        resolved_fld.append(f2)
                else:
                    resolved_fld.append(f)
        else: # look for a field_desc in parent classes
            resolved_fld = None
            for b in bases:
                if hasattr(b,"fields_desc"):
                    resolved_fld = b.fields_desc
                    break

        if resolved_fld: # perform default value replacements
            final_fld = []
            for f in resolved_fld:
                if f.name in dct:
                    f = f.copy()
                    f.default = dct[f.name]
                    del(dct[f.name])
                final_fld.append(f)

            dct["fields_desc"] = final_fld

        newcls = super(Packet_metaclass, cls).__new__(cls, name, bases, dct)
        if hasattr(newcls,"register_variant"):
            newcls.register_variant()
        for f in newcls.fields_desc:                
            f.register_owner(newcls)
        config.conf.layers.register(newcls)
        return newcls

    def __getattr__(self, attr):
        for k in self.fields_desc:
            if k.name == attr:
                return k
        raise AttributeError(attr)

    def __call__(cls, *args, **kargs):
        if "dispatch_hook" in cls.__dict__:
            cls =  cls.dispatch_hook(*args, **kargs)
        i = cls.__new__(cls, cls.__name__, cls.__bases__, cls.__dict__)
        i.__init__(*args, **kargs)
        return i
```

inside the `__call__` method, attempting to solve `cls.__name__` will trigger this exception.

**Comment by takashioomoto** [comment]
All right, here is a working reproduction script, let me know if this works for you:

```
from System.Diagnostics import Debugger
Debugger.Launch()
# ---
class Meta(type):
    def __new__(mcs, name, bases, dict):
        return type.__new__(mcs, name, bases, dict)
    def __getattr__(self, attr):
        raise AttributeError(attr)

class A():
    __metaclass__ = Meta
    def b(self):
        return A.__name__
# ---
from System.CodeDom.Compiler import CompilerParameters
from Microsoft.CSharp import CSharpCodeProvider

params = CompilerParameters()
params.GenerateInMemory = True
params.ReferencedAssemblies.Add('System.Core.dll')
params.ReferencedAssemblies.Add('Microsoft.CSharp.dll')

results = CSharpCodeProvider({"CompilerVersion": "v4.0"}).CompileAssemblyFromSource(params,  """
namespace Foo
{
    public static class Bar
    {
        public static void RunFunc(dynamic obj) { obj(); }
    }
}""")
for e in results.Errors:
    print(e)
assert not results.Errors.HasErrors

import clr
clr.AddReference(results.CompiledAssembly)

from Foo import Bar
# ---
a = A()
for i in range(200):
    print(i)
    Bar.RunFunc(a.b)
```

edit: fixed getattr to a sensible result (even if it never gets to be called)

**Comment by kunom** [comment]
@takashioomoto Thanks! That helped really a lot. 

Reproduction is actually much easier than I thought: 

``` python
class Meta(type):
    def __new__(mcs, name, bases, dict):
        return type.__new__(mcs, name, bases, dict)
    def __getattr__(self, attr):
        raise AttributeError(attr)

class A():
    __metaclass__ = Meta

for i in range(200):
    assert 'A' == A.__name__ # after 100 iterations: see https://github.com/IronLanguages/main/issues/1269
```

For finalizing a PR, I am still a bit uncertain whether `PythonTypeSlot.GetAlwaysSucceeds` really should return true for `Meta.__getattr__`, or whether `MetaPythonType+MetaGetBinderHelper.AddMetaGetAttribute()` is incomplete with regard to finishing its 'ConditionalBuilder' instance. At the moment, I tend towards the latter.

**Comment by takashioomoto** [comment]
But do we want the ConditionalBuilder to be successful? The way I see it `AddMetaGetAttribute()` needs to fail in this case, not finish - otherwise `__getattr__()` of the metaclass is used to find `__name__`, not the expected behavior.

If we could find a repro when the `__getattr__()` of the metaclass is really meant to return an attribute the situation would be different. But this isn't the case:

``` python
class Meta(type):
    def __new__(mcs, name, bases, dict):
        return type.__new__(mcs, name, bases, dict)
    def __getattr__(self, attr):
        if attr == "__foo__"
            return "bar"
        raise AttributeError(attr)
class A():
    __metaclass__ = Meta

for i in range(200):
    print i
    assert 'bar' == A.__foo__ # executes without problem
```

**Comment by kunom** [comment]
A ConditionalBilder is used to dynamically create AST structures in the form of `if (C1) then (A1) else if (C2) then (A2) else .... else (AElse)?`. Not finishing it means that AElse is not defined, which is obviously an issue for the uniformed reader.

The point is that the PythonTypeSlot for `__getattr__` declares itself as always being available. The code generation should therefore not issue "if (try_get_value) then invoke(value);" but "try_get_value; invoke(value);".
