### ISSUE TITLE
Bugs found by analyzing IronLanguages with PVS-Studio

### ISSUE THREAD

**Issue by DieselMachine84** [IronLanguages/main#1270]
I have checked the source code with PVS-Studio and found some bugs and suspicious places.
Here is the link to the article about it: http://www.viva64.com/en/b/0367/
Official page of the analyzer: http://www.viva64.com/en/pvs-studio/

I have attached the full log. It can be viewed with PVS-Studio Standalone, just rename IronLanguages.txt to IronLanguages.plog before open it.
[IronLanguages.txt](https://github.com/IronLanguages/main/files/85482/IronLanguages.txt)

**Comment by slide** [comment]
Is a PVS-Studio Standalone license available for open source projects

**Comment by DieselMachine84** [comment]
No, but trial version is enough to view the log

**Comment by jdhardy** [comment]
Thanks for running this. I'll take a closer look soon.

**Comment by slide** [comment]
All I get is an error that "The version 10.0 of Visual Studio was not found" when I try and open the log.

**Comment by DieselMachine84** [comment]
Can you sand me a stack trace please?

2016-02-23 16:04 GMT+03:00 Alex Earl <notifications@github.com>:

**Comment by slide** [comment]
I don't get a stack trace, just a message box with that message.

**Comment by slide** [comment]
Ok, looks like the "standalone.exe" was not setup to open the plog files. When I opened standalone.exe and then loaded the plog file, I was able to see the information.
