### ISSUE TITLE
repr for floats is inconsistent with CPython

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1271]
Under CPython (2.7.x), `repr` of a float returns the shortest string representation which round-trips back to the value. With IronPython, `repr` returns the representation with 17 digits of precision (which was how CPython did it in 2.6.x).

The function of interest is `__repr__` in `IronPython\Runtime\Operations\FloatOps.cs`.

CPython:

```
>>> repr(0.1)
'0.1'
>>> repr(0.3)
'0.3'
>>> repr(0.8455124082255701)
'0.8455124082255701'
```

IronPython:

```
>>> repr(0.1)
'0.10000000000000001'
>>> repr(0.3)
'0.29999999999999999'
>>> repr(0.8455124082255701)
'0.84551240822557006'
```

**Comment by simplicbe** [comment]
This should be fixed very easily. Should a test case be added or changed for this?

**Comment by slide** [comment]
I thought there was already an issue for this.

**Comment by slozier** [comment]
I also assumed there would already be an issue for this but I had no luck finding it...

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#102
