### ISSUE TITLE
formatting floats using string.format and 'g'

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1275]
Formatting floats using 'g' to format does not always give the correct number of digits.

The issue appears to be somewhere in `DoubleToFormatString` in `IronPython\Runtime\Operations\FloatOps.cs`.

For example, in the following we only get 15 digits:

```
>>> "{:.17g}".format(102.10950286738087)
'102.109502867381'
>>> "{:.16g}".format(102.10950286738087)
'102.109502867381'
```

While I CPython:

```
>>> "{:.17g}".format(102.10950286738087)
'102.10950286738087'
>>> "{:.16g}".format(102.10950286738087)
'102.1095028673809'
```

**Comment by paweljasinski** [comment]
sys.float_info.dig reports 15 for both cpython (linux, cygwin) and ipy
Whatever cpython gives above 15 digits is internal representation which should be discarded.
In case if c the access to digits above 15 is unrestricted, in case of .net it is tricky but possible to get them out.

**Comment by slozier** [comment]
What I understand from the doc of `sys.float_info.dig` is that if you put in a number with 15 or less significant digits and ask for the representation of that number to 15 significant digits then you get the exact same number.

So string.format should still be able to give 16 and 17 digits, it just doesn't guarantee that the output will match the input.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#101
