### ISSUE TITLE
formatting floats using % and and 'g'

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1276]
Formatting floats using 'g' to format does not give the correct number of digits.

The issue appears to be somewhere in `AppendFloat` in `IronPython\Runtime\StringFormatter.cs`.

For example:
```
>>> "%.17g" % 1021095.0286738087
'1021095.029'
```
While in CPython:
```
>>> "%.17g" % 1021095.0286738087
'1021095.0286738087'
```

**Comment by simplicbe** [comment]
Fixed with #1447
