### ISSUE TITLE
Inverse hyperbolic sinus in math module returns nan for all values < -1

### ISSUE THREAD

**Issue by jagaudin** [IronLanguages/main#1284]
When using the asinh function from the math module, it returns nan for any value lesser than -1. 
it seems that the function tries to return a complex number, although the implementation is different from the cmath module (see attached text file).

[Document.txt](https://github.com/IronLanguages/main/files/197324/Document.txt)

Can anyone shade some light on this ?

Edit : 

Reading the code in the attached document, the flaw is in
`if (Math.Abs(v0) > 1.0) {
                return Math.Log(v0) + Math.Log(1.0 + MathUtils.Hypot(1.0, 1.0 / v0));}`

If v0 < -1.0, abs(v0)>1.0 and the function tries to return log(v0) with v0 negative, hence the bug.
math.sign method could be used to fix this : 

`if (Math.Abs(v0) > 1.0) {
                return Math.Sign(v0)*(Math.Log(Math.Abs(v0)) + Math.Log(1.0 + MathUtils.Hypot(1.0, 1.0 / v0)));}
`

**Comment by slide** [comment]
Feel free to create a PR for this.

**Comment by jagaudin** [comment]
Sorry for the delay.
