### ISSUE TITLE
Random Results Differs From Native Python

### ISSUE THREAD

**Issue by marco-ruas** [IronLanguages/main#1286]
When using the random module from python from within a C# application (.NET framework 4.0) via IronPython (2.7.5) the results are different from what we get from native Python (2.7.8), we only came to know that recently when we started a GLI Approval process ([http://www.gaminglabs.com](url)) in an attempt to certify the randomness of our gaming application so that we could supply it to many different countries where the GLI standards have to be met (we have been using this C# + IronPython configuration for years and it all seemed to work fine without the in depth evaluation from GLI).
When submitting random numbers generated from native python GLI accepts them as they pass the whole DieHard testing standards ([https://en.wikipedia.org/wiki/Diehard_tests](url)) when we do the same thing via IronPython something hapens that makes the results unacceptable to GLI standards.
Could there be some configuration, patch, update, extra module or something that we could change/add to our environment to make IronPython generate exactly the same results we get directly from native Python?
I am attaching both codes that generate GLI accepted (NativePythonRandom.py) and rejected results (IronPythonRandom.cs) inside this file [SampleCode.zip](https://github.com/IronLanguages/main/files/230537/SampleCode.zip), we could not figure out what could be different among these two simple programs and hope there is a short way to make it work so that we can use the well structured and stable debugged math python module we have developed over the years without the need to transcript it into C# to make it meet the GLI standards.

**Comment by rassilon** [comment]
IronPython utilizes .Net's System.Random class for generating random numbers. I believe there are .Net versions of the random number generator that Python uses. You could use one of those instead. See http://stackoverflow.com/questions/1166408/c-sharp-mersenne-twister-random-integer-generator-implementation-sfmt-monte-ca for some pointers.

**Comment by marco-ruas** [comment]
Thanks for the suggestion on the thread but I have already considered recompiling the full Random class code using Python's source code, and I really think this would solve the problem as it would then use native Python's random code instead of IronPython's, which has already proven to meet the certification requirement but this would require an amount of work that is not going to payout as opposed to the other solution which is (unfortunately!) rewrite the math code in C# and give up mixing C# and Python on the same application.
