### ISSUE TITLE
Import error: no module named copyreg

### ISSUE THREAD

**Issue by TimHaydnJones** [IronLanguages/main#1288]
Hi all - hope you don't mind a numpty asking what might be a dumbass question.
I have successfully used a python project called pychromecast.
I am trying to use the same project in IronPython
I think I have installed the module OK using ipy -X:FullFrames setup.py install (where setup.py relates to chromecast) but when I startup IronPython, it reports an Import error: no module named copyreg.
This doesn't happen in python, only ironpython.
Also, what I don't get is that if I manually import copyreg from the IronPython console, it works OK, so it's obviously present and correct.
Any advice would be much appreciated.
Cheers all
Tim

![image](https://cloud.githubusercontent.com/assets/15029388/14980130/a6a8b66a-111e-11e6-850c-ed7a8bca6623.png)

**Comment by slide** [comment]
Can you specify a link to the pychromecast package?

**Comment by TimHaydnJones** [comment]
I think it was this one

https://github.com/balloob/pychromecast

**Comment by slide** [comment]
It looks like this is related to the following:

https://github.com/google/protobuf/blob/master/python/google/protobuf/internal/python_message.py#L58

It's trying to import from the six package, and then if that fails it tries to use copy_reg as copyreg. I don't know why they are doing this, or if it is correct.

**Comment by slide** [comment]
If I open an ipy console and try and import copyreg, I get 

```
ImportError: No module named copyreg
```

Do you have the Python 3.x stdlib in your path for ipy?

**Comment by slide** [comment]
FYI, it looks like pychromecast depends on some native modules, so it won't work with IronPython.

**Comment by slide** [comment]
This is an issue with PIP that should be resolved once we get the next release out. My previous comment about native modules still applies though.
