### ISSUE TITLE
kwargs expansion strangeness

### ISSUE THREAD

**Issue by swn1** [IronLanguages/main#1290]
While working on importing the jupyter_client library in IronPython 2.7.5 on the 4.0 framework I ran into a very strange bug.  It may be difficult to reproduce so I'll just report what I saw and maybe somebody can Zen it.  Or I can try to create a repro case, it was pretty stable in-context on my machine.

There was a call site that built dictionary by pasting together the contents of other dictionaries and passed that as **kwargs to a __init__ of a class that was expecting a **kwargs.  It failed, robustly, with the "keywords must be strings"  TypeError.

Making a copy of the dictionary works around the problem: https://github.com/swn1/traitlets/commit/296365a3713131e1bf0279f3861891942c5e6ccb

map(type) over kwargs.keys shows the keys are all strings and the dictionary itself begins as a literal {}.  Seems pretty clear to me it's a bug but I'm a beginner.

`map(type,kwargs.keys())
[<type 'str'>, <type 'str'>, <type 'str'>, <type 'str'>, <type 'str'>, <type 'str'>, <type 'str'>, <type 'str'>, <type 'str'>]
def foo(**kw): pass
None
foo(**kwargs)
error: foo() keywords must be strings
foo(**dict(kwargs.items()))
None
`

One of the values is unpickleable but if I delete that key I still get the same error.  The pickle of the dictionary is 
`"(dp0\nS'ip'\np1\nS'127.0.0.1'\np2\nsS'hb_port'\np3\nI33954\nsS'shell_port'\np4\nI33950\nsS'transport'\np5\nS'tcp'\np6\nsS'stdin_port'\np7\nI33952\nsS'control_port'\np8\nI33953\nsS'connection_file'\np9\nS'c:\\\\users\\\\steve\\\\appdata\\\\local\\\\temp\\\\2\\\\tmpladydz.json'\np10\nsS'iopub_port'\np11\nI33951\ns."
`
But unpickling it is a copy operation and the copy works fine, as in the work-around.

**Comment by swn1** [comment]
Deleting all the keys from the dictionary one-by-one, it continues to fail until the last key is deleted, then it works.  Re-running to the breakpoint and deleting just that last key, it still fails.  Other non-empty dictionaries passed to the same function work fine.  It's something history dependent and I don't have any idea how to figure out what it might be.

**Comment by jdhardy** [comment]
This is the sort of bug that's going to require stepping through, I think. A minimal repro would be helpful, or even instructions on how to get the necessary bits running.

**Comment by swn1** [comment]
I have a set of interrelated branched forks.  Running the installed ipy64 2.7.5 from Visual Studio 2015, my top-level script resets sys.path to a copy of the Lib folder as deployed by the NuGet package.

I've run ensurepip, and installed
decorator 4.0.9
enum 0.4.6-py2.7
six 1.10.0

I then symbolically linked into the Lib directory the lib subdirectories from local clones on these repos:
https://github.com/swn1/ipython_genutils.git
https://github.com/swn1/jupyter_client.git
https://github.com/jupyter/jupyter_core.git
https://github.com/swn1/traitlets.git
https://github.com/swn1/pyzmq.git

Note all of the modified forks default to a branch named ironpython; all of my changes are isolated to those branches.

Then clone my fork of clrzmq4 https://github.com/swn1/clrzmq4.git and build it (debug / anycpu).  Deploy the resulting ZeroMQ.dll into the Lib\jupyter_client\backend\cli folder and put the amd64 and i386 folders (containing libzmq and libsodium native dlls) into the ironpython installation direcotry (siblings of ipy.exe)

Now you should be able to say import jupyter_client and it will succeed.  If you back out the workaround mentioned above it should reproduce the failure.  It's a log to go though but trying to create a repro of a bug state that won't survive copying the object involved is also a lot of work.

**Comment by swn1** [comment]
Nobody else has tried to follow me on this journey yet, I'd be very grateful for any feedback at all.

**Comment by jdhardy** [comment]
I can't promise I'll get to it right away but I'll give it a try. It's a
very odd bug, that's for sure.

On Fri, May 13, 2016 at 6:56 AM, Stephen W. Nuchia <notifications@github.com

**Comment by slide** [comment]
We're trying to triage issues, was this ever resolved?

**Comment by swn1** [comment]
I am not aware of any resolution.

**Comment by thimolangbehn** [comment]
Here is a minimal example which reproduces the problem on 2.7.5:

```python
# the presence of positional parameters does not change anything
def bar(a=2):
    pass

def foo(*args, **kwargs):
    opts = {'d':True, 'a':None}
    opts.update(kwargs)
    del opts['d']
    
    bar(**opts)
    # rebuild dictionary to avoid issue 1290.
    #bar(**{k:v for k,v in opts.items()})

foo()
```

**Comment by slide** [comment]
@thimolangbehn Thanks for the repro case. Will look into it.
