### ISSUE TITLE
Configuration=v2Release depends on v3.5 System.Core

### ISSUE THREAD

**Issue by HinTak** [IronLanguages/main#1291]
```
xbuild Solutions/IronPython.sln /p:Configuration="v2Release"
```

works for current mono, but it doesn't actually do v2, but v3.5. This is confusing as I was compiling for v2 (and pure v2), and took ages trying to figure out why it is still asking for 3.5 System.Core under a v2 runtime.

There are at least two places in Solutions/Common.proj for v2 which needs changing - one is the "TargetFrameworkVersion", the other is "Reference Include".

FWIW, the 2.6.2 for net 2 sp2 binary seems to be sufficient for my purpose...

v2Release really needs better documenting...

**Comment by HinTak** [comment]
Is there any git tags for the 2.6.2 src's (both versions)?

**Comment by HinTak** [comment]
I'll give one reason for sticking with net2: mixed mode assemblies. They don't work at all with mono and unlikely ever to, and not work wine + the default wine-mono emulation of dotnet either. But they do work with wine + genuine ms dotnet (dotnet2). Unfortunately dotnet3/dotnet4 don't work well with wine.

So If you are on non-windows, but have a x86/x64 processor on mac os x/linux, your option of running a mixed mode assembly application is exactly one: use it under wine with dotnet2.

**Comment by slide** [comment]
Feel free to create a PR for this.

**Comment by slide** [comment]
I don't think we will be able to support a pure .NET 2.0 version of IronPython. Older source releases are available on CodePlex (https://ironpython.codeplex.com) if you want to try to continue to use 2.6.x

**Comment by HinTak** [comment]
Fairly enough - perhaps I was asking for Configuration="v2Release better documented, or even withdrawn (i.e. called it "v35Release").

**Comment by HinTak** [comment]
I _am_ continuing to use 2.6.x , in one of my branches:

https://github.com/HinTak/Font-Validator/commit/0a188ce6c1a7a2c1e8e8dcc491052702cc5dd951
