### ISSUE TITLE
Tracing does not work

### ISSUE THREAD

**Issue by jpmaterial** [IronLanguages/main#1296]
The example for programmatic tracing with the trace module as given in the docs (https://docs.python.org/2.7/library/trace.html#programmatic-interface) works for me only after some hacking (see bottom).

Without the hacks I got
Traceback (most recent call last):

  File "./trace_test.py", line 38, in <module>
  File "C:\MinGW\msys\1.0\bin\Lib\trace.py", line 510, in run
  File "<string>", line 1, in <module>
  File "C:\MinGW\msys\1.0\bin\Lib\trace.py", line 607, in globaltrace_lt

AttributeError: 'NoneType' object has no attribute 'get'

With only the globaltrace_lt() hack I got:

Traceback (most recent call last):

  File "./trace_test.py", line 42, in <module>
  File "C:\MinGW\msys\1.0\bin\Lib\trace.py", line 328, in write_results
  File "C:\MinGW\msys\1.0\bin\Lib\trace.py", line 406, in find_lines
  File "C:\MinGW\msys\1.0\bin\Lib\trace.py", line 397, in find_lines_from_code
  File "C:\MinGW\msys\1.0\bin\Lib\trace.py", line 448, in find_executable_linenos
  File "C:\MinGW\msys\1.0\bin\Lib\dis.py", line 184, in findlinestarts

NotImplementedError

I'm using PythonContext 2.7.5.0 on .NET 4.0.30319.42000

My hacks:

```
def main():
    print 'hello world'


import sys
import trace


import dis

def fake_globaltrace_lt(self,frame,why,arg):
    return self.localtrace

dis.real_findlinestarts=dis.findlinestarts

def fake_findlinestarts(code):
    if 'co_lnotab' in dir(code):
        dis.real_findlinestarts(code)
    else:
        print dir(code)
        yield (0,0)

dis.findlinestarts=fake_findlinestarts

trace.Trace.globaltrace_lt=fake_globaltrace_lt


# create a Trace object, telling it what to ignore, and whether to
# do tracing or line-counting or both.
tracer = trace.Trace(
    ignoredirs=[sys.prefix, sys.exec_prefix],
    trace=1,
    count=1)

# run the new command using the given tracer
tracer.run('main()')

# make a report, placing output in the current directory
r = tracer.results()
r.write_results(show_missing=True, coverdir="cover")

```

**Comment by slide** [comment]
@markusschaber You mentioned you guys use tracing in your stuff, can you take a look at this?

**Comment by slide** [comment]
@kunom Any comments?

**Comment by kunom** [comment]
The first issue is a TracebackFrame instance that is constructed with a `scopeCallback` argument instead of a `globals` PythonDictionary, but the dictionary returned by scopeCallback does hold `null` as value for "$globalContext".

**Comment by kunom** [comment]
It is actually a systematic issue that "$globalContext" is not initialized at the time of the "call" trace event when entering a function. Only on subsequent "line" trace events.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#99
