### ISSUE TITLE
default IronPython build target does not work for mono, needs  /p:Configuration="v2Release" 

### ISSUE THREAD

**Issue by HinTak** [IronLanguages/main#1297]
Building on linux mono requires the /p:Configuration="v2Release" config, or it fails looking for  MonoAndroid,Version=v2.2 . 

ipy-2.7.5]$ xbuild Solutions/IronPython.sln /p:Configuration="v2Release"
	 25 Warning(s)
	 0 Error(s)

Time Elapsed 00:00:57.1559790

ipy-2.7.5]$ xbuild Solutions/IronPython.sln
	 2 Warning(s)
	 151 Error(s)

Time Elapsed 00:00:13.0384820

2b528dccee9e973b94ac00a0dbc14b0ebb030c6d]$ xbuild Solutions/IronPython.sln
	 2 Warning(s)
	 151 Error(s)

Time Elapsed 00:00:11.3500930

2b528dccee9e973b94ac00a0dbc14b0ebb030c6d]$ xbuild Solutions/IronPython.sln /p:Configuration="v2Release"

	 27 Warning(s)
	 0 Error(s)

Time Elapsed 00:01:03.6721490

**Comment by HinTak** [comment]
Interestingly, xbuild Solutions/IronPython.sln /p:Configuration="Release" almost works:

	socket.cs(1901,63): error CS0117: `System.Net.Sockets.SocketOptionName' does not contain a definition for `IPv6Only'

	 18 Warning(s)
	 1 Error(s)

Time Elapsed 00:00:57.1719150

**Comment by HinTak** [comment]
I think the IPv6Only issue is known and work-arounded somehow, but I don't have the reference off hand, just remembered reading about it.

**Comment by HinTak** [comment]
Argh, it is conditional on FEATURE_IPV6 , which could be turned off, and probably is, for v2Release.

**Comment by slide** [comment]
On *NIX you should use the makefile to build Mono. There is still an error with IPv6Only, but the other errors are not there.

**Comment by slide** [comment]
The error with ipv6only has been resolved. Please use the makefile to build with mono
