### ISSUE TITLE
Chinese site offers "Microsoft IronPython2.7.6" for download, but seems to be just win32 python

### ISSUE THREAD

**Issue by HinTak** [IronLanguages/main#1298]
Was looking for 2.7.6 release plan and info, and found this:
http://download.pchome.net/development/linetools/download-21826.html

and one of the urls for download
http://dl-sh-ctc-1.pchome.net/0g/ua/python-2.7.6.msi

it seems to be just win32 python. I haven't actually installed it though.

You probably want to contact them and correct them...

**Comment by slide** [comment]
This isn't really something we will do. It may be confusing, but there are lots of places that we would have to deal with and we just don't have the man power.
