### ISSUE TITLE
Exception while executing a compiled function

### ISSUE THREAD

**Issue by shyampundkar** [IronLanguages/main#1303]
I am getting exception from IronPython 2.7.5 when I tried executing a compiled function.
The existing code working fine on ironpython 2.7.3 

 compiledFormula.Execute(scope); **// ran successfully**
Engine.Execute<double>("F_" + id.ToString("N") + "()", scope); **// throws below exception**

Please guide!

   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Scripting.Utils.ExceptionUtils.GetData(Exception e, Object key)
   at IronPython.Runtime.Exceptions.PythonExceptions.GetFrameList(Exception e)
   at IronPython.Runtime.Operations.PythonOps.UpdateStackTrace(Exception e, CodeContext context, FunctionCode funcCode, Int32 line)
   at Microsoft.Scripting.Interpreter.ActionCallInstruction`4.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.Interpreter.HandleException(InterpretedFrame frame, Exception exception)
   at Microsoft.Scripting.Interpreter.Interpreter.Run(InterpretedFrame frame)
   at Microsoft.Scripting.Interpreter.LightLambda.Run2[T0,T1,TRet](T0 arg0, T1 arg1)
   at IronPython.Compiler.PythonScriptCode.RunWorker(CodeContext ctx)
   at IronPython.Compiler.PythonScriptCode.Run(Scope scope)
   at IronPython.Compiler.RuntimeScriptCode.InvokeTarget(Scope scope)
   at IronPython.Compiler.RuntimeScriptCode.Run(Scope scope)
   at Microsoft.Scripting.SourceUnit.Execute(Scope scope, ErrorSink errorSink)
   at Microsoft.Scripting.SourceUnit.Execute(Scope scope)
   at Microsoft.Scripting.Hosting.ScriptSource.Execute(ScriptScope scope)
   at Microsoft.Scripting.Hosting.ScriptEngine.Execute(String expression, ScriptScope scope)
   at Microsoft.Scripting.Hosting.ScriptEngine.Execute[T](String expression, ScriptScope scope)

**Comment by slide** [comment]
What does the function look like? Can you provide a simple reproduction case?

**Comment by shyampundkar** [comment]
If I replace the values in the function will look like 

0 / ((0 + 0)/2)

**Comment by slide** [comment]
Please provide a reproduction case.

**Comment by shyampundkar** [comment]
I have created a sample Silverlight application for you. But I am unable to attach the zip file here.

**Comment by shyampundkar** [comment]
Can you give me a mail Id so that I will send a secured delivery to it?

**Comment by simplicbe** [comment]
That's not a good way. Please provide the relevant parts of the source code. If there is some part which must be protected, please obfuscate them by dummy values and so on.

**Comment by shyampundkar** [comment]
Below code is from MainPage.xaml.cs from Silverlight applicatio. I get exception at the line marked as bold.
-------------------------------------------
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Shapes;
using IronPython.Hosting;
using Microsoft.Scripting.Hosting;

namespace ironpythonSilverlightIssue
{
    public partial class MainPage : UserControl
    {
        public MainPage()
        {
            InitializeComponent();
            Program.Main(null);
        }
    }


    internal class Program
    {
  
        private static readonly Dictionary<Guid, CompiledCode> CompiledCodes = new Dictionary<Guid, CompiledCode>();

        protected ScriptScope ScriptScope { get; private set; }

        private static readonly ScriptEngine Engine = CreatePythonEngine();

        private static ScriptEngine CreatePythonEngine()
        {
            var setup = Python.CreateRuntimeSetup(null);
            setup.HostType = typeof (Microsoft.Scripting.Silverlight.BrowserScriptHost);
            var runtime = new ScriptRuntime(setup);
            return Python.GetEngine(runtime);
        }

        public static void Main(string[] args)
        {


            var key = new Guid("CED996A4-59FB-67CE-2DC6-39BFFED18130");
            const string formula = "0 / ((0 + 0)/2)";
            CompiledCode compiledFormula = CreateCompiledFormula(key, formula);
            ScriptScope scope = Engine.CreateScope();

            compiledFormula.Execute(scope);

            **var result = Engine.Execute<double>(GetCompiledFunctionName(key) + "()", scope);**

        }

        private static CompiledCode CreateCompiledFormula(Guid id, string formula, string exceptReturn = "return float('nan')")
        {
            formula = SanitizeCode(formula, false);

            const string wrapper = @"
def {0}():
    try:
        return {1}
    except ArithmeticError:
        {2}";

            var functionName = GetCompiledFunctionName(id);

            var wrappedFormula = string.Format(CultureInfo.CurrentCulture, wrapper, functionName, formula, exceptReturn);

            return Engine.CreateScriptSourceFromString(wrappedFormula).Compile();
        }

        private static string GetCompiledFunctionName(Guid id)
        {
            return "F_" + id.ToString("N");
        }

        private static string SanitizeCode(string code, bool allowLineBreaks)
        {
            string sanitizedCode = code;

            sanitizedCode = sanitizedCode.Trim();

            if (allowLineBreaks)
                sanitizedCode = Regex.Replace(sanitizedCode, @"\t+", @" ");
            else
                sanitizedCode = Regex.Replace(sanitizedCode, @"\s+", @" ");

            sanitizedCode = Regex.Replace(sanitizedCode, @";", string.Empty);

            return sanitizedCode;
        }
    }

}

**Comment by shyampundkar** [comment]
Dear Slide, Could you please update regarding status of this issue?
I need to integrate latest version of ironpython in our application.

**Comment by slide** [comment]
I will look into a fix before the final IronPython 2.7.6

**Comment by slide** [comment]
I ran this with just a normal console application and I didn't get an exception. Can you try the same to see if it is isolated to Silverlight? I don't have a Silverlight development environment.

**Comment by shyampundkar** [comment]
Hi Slide, yes its specific to silver light. We are successfully using 2.7.3 with silverlight. But now our team has got a request to upgrade iron python to latest version so I tried 2.7.5 and got this error. So do you mean that iron python do not support silver light anymore?

**Comment by slide** [comment]
We haven't tested Silverlight for some time, so I am not surprised that it isn't working. I will try and setup a Silverlight development environment to look into this. One thing to note is that 2.7.6 will not distribute Silverlight assemblies, so I am not sure you will really want to upgrade.

**Comment by shyampundkar** [comment]
Thank you so much Slide for looking into it! We are ready to upgrade to a version which supports silver light. So if you are planning to fix this issue in 2.7.5 we will upgrade to it.

**Comment by slide** [comment]
I was planning on fixing it before I determined it was isolated to
silverlight. As I mentioned, 2.7.6 will not distribute silverlight
assemblies, and silverlight will not be supported going forward unless
someone who is invested in needing silverlight support steps forward to
work on it.

**Comment by shyampundkar** [comment]
If I understood correctly then this issue won't be fixed.

**Comment by slide** [comment]
I readded the silverlight assemblies to the installer for RC3 and fixed the issue. Fix will be in 2.7.6

**Comment by shyampundkar** [comment]
Thank you so much Slide! I am really grateful to you for your help!

**Comment by slide** [comment]
I'll release another RC soon, please test it when it is released.

**Comment by shyampundkar** [comment]
Sure! I will test it when it is released and let you know how it goes. Thanks a lot Slide!

**Comment by shyampundkar** [comment]
Could you please let me know when will 2.7.6 be released?

**Comment by slide** [comment]
Final is end of next week.
