### ISSUE TITLE
Can't build ironruby on UNIX Systems

### ISSUE THREAD

**Issue by amiralles** [IronLanguages/main#1304]
Hi guys, I been trying to build ironruby using this command:

```
xbuild /p:configuration=Release Solutions/Ruby.sln
```

And got this error:
"...Builtins/RubyModule.cs(1767,21): error CS1570: Warning as Error"... blah, blah, blah....
(It's an xml error in the method's summary).

It fails on both, Mac and Linux (Ubuntu 14). On the mac I'm using mono v 4.2.1.
I already fixed it on a local branch, can I send a pull request with my changes or doesn't work just like that?

PS: I know that this is something specific to ironruby, but based on brief exploration, I guess that the build process is centralized at the main repository, so maybe this is the right place to report the issue. I really don't know... any guidance will be appreciated.
Thanks.

**Comment by slide** [comment]
I would recommend doing all changes in the ironruby repo.

**Comment by amiralles** [comment]
All right. I'll do that then.
Just another question: Now that you are splitting projects,  wouldn't be better for each project/repo to have its own build script? 
i.e.  if I checkout ironruby I can build it without knowing anything about ironpython or ironlanguages at all.
I guess as of now, because of the dependencies, it cant' be done. How do you plan to handle that?

**Comment by slide** [comment]
The ironruby has its own build script, but it still has to depend on the
dlr somehow. Its currently pulling in a prerelease via nuget. We're going
to do a full release of the dlr somewhat soon and then the separate repos
can just depend on that.

**Comment by amiralles** [comment]
That'll be great. Thanks.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironruby#10
