### ISSUE TITLE
Script error: __init__() takes at least 6 arguments (5 given)

### ISSUE THREAD

**Issue by shrikantkaramkar** [IronLanguages/main#1307]
I am using redirect_request.py to redirect multiple urls.
On executing this py I am getting following error:

```
Script error:
__init__() takes at least 6 arguments (5 given)
```

I am using following mitm method to redirect:

```
from mitmproxy.models import HTTPResponse
from netlib.http import Headers


def request(flow):
    # pretty_host takes the "Host" header of the request into account,
    # which is useful in transparent mode where we usually only have the IP
    # otherwise.

    # Method 1: Answer with a locally generated response
    if flow.request.pretty_host.endswith("example.com"):
        resp = HTTPResponse(
            b"HTTP/1.1", 200, b"OK",
            Headers(Content_Type="text/html"),
            b"helloworld"
        )
        flow.reply.send(resp)
```

`mitmproxy version: 0.17`
`OS: MAC OSX Yosemite 10.10.5`

**Comment by shrikantkaramkar** [comment]
I tried with passing 6 arguments, 7 arguments but still this error persists,

**Comment by shrikantkaramkar** [comment]
This is the init of HTTPResponse
```
def __init__(
            self,
            http_version,
            status_code,
            reason,
            headers,
            content,
            timestamp_start=None,
            timestamp_end=None,
            is_replay = False
    )
```

copied from source code

**Comment by simplicbe** [comment]
@shrikantkaramkar how do you have installed the `mitmproxy` module? Using `ipy -X:Frames -m pip install mitmproxy`?

**Comment by shrikantkaramkar** [comment]
steps:
1. Downloded the zip from github
2. installed using python setup.py install
3. Came across few library issues and resolved them.

Let me if there is better way to install latest versions and upgrade mitmproxy.

Thanks
Shrikant

**Comment by simplicbe** [comment]
@shrikantkaramkar I currently try to install it using `ipy -X:Frames -m pip install mitmproxy` but some errors occurse. I try to solve them, cause this should be the way to install the module. But I'll also try to reproduce it the way you have installed the module. Thanks for your quick answer.

**Comment by shrikantkaramkar** [comment]
ipy -X:Frames -m pip install mitmproxy

You run above command after downloading the code from github.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#98
