### ISSUE TITLE
NullReferenceException in PythonContext.cs

### ISSUE THREAD

**Issue by lafrank** [IronLanguages/main#1329]
I am working on a c# application that provides Python script debugging capabilities. To achieve this functionality I set a traceback handler with Engine.SetTrace(MyTracebackHandler).
My code works correctly with version 2.7.5, however it crashes with release 2.7.6 due to a NullReferenceExeption occurring in PythonContext at the below location:
```c#
internal void PushTracebackHandler(PythonTracebackListener listener) {
            var tracebackListeners = _tracebackListeners.Value;
            if (_debugContext != null) {
                while (tracebackListeners.Count > 0 && tracebackListeners.Peek().ExceptionThrown) {
                    // remove any orphaned traceback listeners that are just doing pops
                    tracebackListeners.Pop();
                }
                tracebackListeners.Push(listener);
            }
        }
```
The problem is that  the first debug session works correctly, but all subsequent calls fail as _tracebackLiteners.Value is null for some reason.. I suspected that my call to Engine.SetTrace(null) is invalid at the end of a debug session, but as much as I can check this is the correct way to stop debugging. And again, this works correctly with version 2.7.5.

**Comment by lafrank** [comment]
What I see, is that the _tracebackListeners.Value stack is instantiated at the call to EnsureDebugContext() from inside PythonContext constructor. As I can't see any other assignments, I wonder how and why it gets nulled ? Or perhaps has it never been instantiated ? Can't figure out...

**Comment by simplicbe** [comment]
@lafrank are you able to set a breakpoint to the `Value`-Setter and where `trancebackListener` is instanciated? Maybe you could go down the stacktrace (IP code) and see what happens there.

**Comment by lafrank** [comment]
Not easily, as _tracebackListenmers is the type of ```Microsoft.Scripting.Utils.ThreadLocal<Stack<PythonTracebackListener>>``` . I'll need check how to fin the source, I guess it is in DLR.
I'll try to create a simple and small example to reproduce the issue.
