### ISSUE TITLE
issues reported by PVS

### ISSUE THREAD

**Issue by paweljasinski** [IronLanguages/main#1335]
http://www.viva64.com/en/examples/ search for ironpython

**Comment by slide** [comment]
I already took care of this, they opened an issue.

**Comment by slozier** [comment]
@slide There are a number of other issues listed on the site.

**Comment by slide** [comment]
Some of the issues affect IronRuby and others were not actually pertinent. We're there specific ones that you saw?

**Comment by slozier** [comment]
V3001 was one I happened to look at and which is still there so I assumed there might be other ones. But I didn't look at it in details...

https://github.com/IronLanguages/main/blob/4cb8abc569d98ddadd2d67573c2dbd7dcc39b548/Languages/IronPython/IronPython/Runtime/Operations/ObjectOps.cs#L456

**Comment by slide** [comment]
This is where I made the changes. fdd036

**Comment by slide** [comment]
See #1270

The one mentioned above is the only one I missed. The others I didn't think applied because they were in the parser, which usually contains a little "wackiness"
