### ISSUE TITLE
Issue with Ast

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1338]
The following C# program is failing:
```
ScriptRuntime runtime = Python.CreateRuntime();
ScriptEngine engine = runtime.GetEngine("IronPython");
ScriptScope scope = runtime.CreateScope();
ScriptSource src = engine.CreateScriptSourceFromString(@"
import System
somecallable = System.Func[object](lambda: 'Delegate')
print somecallable()
");
src.Execute(scope);
```
It broke in this commit: 247e6dbffba4898434ad95c5341552575fb2476a

It's failing with a `NullReferenceException` at:
https://github.com/IronLanguages/main/blob/ipy-2.7-maint/Languages/IronPython/IronPython/Compiler/Ast/Node.cs#L203

**Comment by simplicbe** [comment]
Ok, the assert call is failing...

**Comment by slide** [comment]
Can this be closed out then?

**Comment by slozier** [comment]
Yes, we should reopen the PR though...
