### ISSUE TITLE
Issue with Overloads causing test_cliclass_20 to fail

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1343]
test_cliclass_20 started failing with IronLanguages/main/pull/1265. In particular, to reproduce:
```
min.Overloads[object, object]
```
This is raising a `TypeError` exception where as before it succeeded.
```
TypeError: No match found for the method signature min[Object, Object]. Expected [CodeContext, Object], [CodeContext, Object, Object], [CodeContext, Object[]], [CodeContext, Object, IDictionary`2], [CodeContext, Object, Object, IDictionary`2], [CodeContext, IDictionary`2, Object[]]
```

I'm not sure if raising here is the correct behaviour. Shouldn't the `CodeContext` parameter be excluded?

@simplicbe since this is your PR can you take a look?

**Comment by simplicbe** [comment]
Problem is solved, pull requests is on its way
