### ISSUE TITLE
Include Program-Data-Base (PDB) files in binary Releases

### ISSUE THREAD

**Issue by thimolangbehn** [IronLanguages/main#1364]
PDB files contain debug information for the DLLs. Withouth them, traces parts of the DLLs can not be named. This make Debugging harder for Applications that use IronPython.

**Comment by jdhardy** [comment]
PDBs are quite large to include everywhere, but an extra package or
inclusion on http://www.symbolsource.org/ would be useful.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#96
