### ISSUE TITLE
__slots__ should not have an effect if it is missing in any of the base classes

### ISSUE THREAD

**Issue by ita1024** [IronLanguages/main#1374]
The Consumer thread in the following snippet will raise an exception: `'Consumer' object has no attribute '_Verbose_verbose'`:

``` python
import threading
class Consumer(threading.Thread):
    __slots__= ('task', )
    def __init__(self, task):
        threading.Thread.__init__(self)
        self.task = task
        self.setDaemon(1)
    def run(self):
        print "processing task", self.task

obj = Consumer(object())
obj.start()
import time
time.sleep(5)
```

After commenting the `__slots__` assignment, the execution will display 'processing task' as expected.

**Comment by kunom** [comment]
Most probably, the title should be "`__slots__` should not have an effect if it is missing in any of the base classes".

Excerpt from the Python documentation:

> When inheriting from a class without **slots**, the **dict** attribute of that class will always be accessible, so a **slots** definition in the subclass is meaningless.

**Comment by ita1024** [comment]
I thought it would be worth reporting this behavior. When is the next release going to be made by the way?

**Comment by kunom** [comment]
A somewhat minimal reproduction case:

``` python
class A(object):
    def __init__(self):
        self.a = 0 # fails with "AttributeError: 'C' object has no attribute 'a'"
class B(A):
    def __init__(self):
        super(B, self).__init__()
        self.b = 1 # fails with "AttributeError: 'C' object has no attribute 'b'"
class C(B):
    __slots__ = ('c', )
    def __init__(self):
        super(C, self).__init__()
        self.c = 1
c = C()
print(c.__slots__)
print(c.__dict__)
```

Note: The code including the assignment to `self.b` does work if `B` directly derives from `object`.
