### ISSUE TITLE
sys.settrace is no longer thread safe

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1375]
It appears that `sys.settrace` throws an exception when called from multiple threads. Looks like it broke in #1250.

Here's my analysis. The important part if that `_tracebackListeners` is a `ThreadLocal` so that `Value` is different on each thread:
1. (Thread 1) calls sys.settrace(something)
2. (Thread 1) `sys.settrace` calls `EnsureDebugContext` on the `PythonContext`
3. (Thread 1) initializes `_tracebackListeners` and sets `_tracebackListeners.Value` on the `PythonContext`
4. (Thread 1) does other stuff
5. (Thread 2) calls sys.settrace(something)
6. (Thread 2) `sys.settrace` calls `EnsureDebugContext` on the `PythonContext`
7. (Thread 2) `_tracebackListeners` already initialized so it doesn't set `_tracebackListeners.Value`
8. (Thread 2) goes into `PushTracebackHandler` and tries to use `_tracebackListeners.Value` which is `null`... results in an exception

Some repro code adapted from a test case:

```
import sys
import thread
import time

def test_settrace():
    # verify thread safety of sys.settrace
    global done
    done = 0
    lock = thread.allocate_lock()

    def starter():
        def tracer(*args):
            return tracer

        def test_thread():
            global done
            try:
                sys.settrace(tracer)
                time.sleep(0.1)
            except Exception as e:
                print e
            with lock: done += 1

        thread.start_new_thread(test_thread, ())

    cnt = 2

    for _ in xrange(cnt):
        starter()

    while done != cnt:
       pass

test_settrace()
```

**Comment by kunom** [comment]
See also #1329 for a similar bug.
