### ISSUE TITLE
intern doesn't work with .NET Core

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1381]
The builtin `intern` method uses `String.Intern` which is not available as of `netstandard1.6`. I don't have a workaround so this method is simply excluded when compiling for .NET Core.

`String.Intern` appears to be tagged for the 1.2 milestone. See https://github.com/dotnet/corefx/issues/10216.

@terrajobst

**Comment by terrajobst** [comment]
`String.Intern` will be added in .NET Standard 2.0, which will also be implemented by .NET Core:
- https://github.com/dotnet/standard/blob/master/netstandard/ref/mscorlib.cs#L3048
