### ISSUE TITLE
FEATURE_ENCODING doesn't work on .NET Core

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1392]
FEATURE_ENCODING doesn't work on .NET Core due to a number of missing APIs:
- System.Text.Encoding.GetEncodings
- System.Text.EncodingInfo
- System.Text.Encoding.set_DecoderFallback(System.Text.DecoderFallback)
- System.Text.Encoding.set_EncoderFallback(System.Text.EncoderFallback)

It looks like they may be added in the 1.2 milestone: https://github.com/dotnet/corefx/issues/9583

We may be able to turn on some of the functionality without these. I will have to look at it some more.

@terrajobst

**Comment by terrajobst** [comment]
Yes, all four APIs are planned to come as part of .NET Standard 2.0 and thus will also be available in .NET Core:
- https://raw.githubusercontent.com/dotnet/standard/master/netstandard/ref/mscorlib.cs
