### ISSUE TITLE
can't use pip in embedded intepreter based on NuGet packages

### ISSUE THREAD

**Issue by swn1** [IronLanguages/main#1413]
In an application with an embedded IronPython intepreter based on the 2.7.5 NuGet packages, there is no way to use pip.  Packages need to invoke a command-line interpreter to run their setup scripts and ...

1) If you try to run PIP (or ensurepip) in-process it fails to find a command-line interpreter at all.
2) the NuGet packages don't include ipy.exe so you can't simply invoke it with subprocess; you have to add it to your product build.

Dell Statistica 13.2 will be shipping with a workaround that
1) adds ipy.exe from the full installer to the footprint laid down by the NuGet packages
2) sets -X:Frames and ensures the user's roaming profile has the site-packages folder created
3) includes a script that mocks import for packages that may need to be installed, using the --user flag
so that the user does not need write permission into the application install folder.

It's all working but it could be a lot smoother.

**Comment by swn1** [comment]
Actually there's another issue, we're using a custom name for the Lib subfolder.  If we run pip manually with IRONPYTHONPATH set appropriately and without the --user flag, it creates a Lib\site-packages folder and installs into it.  Then the packages can't be found because they're not on the path!

**Comment by swn1** [comment]
Third problem, if you import sire prior to running ensurepip or pip with the --user flag for the first time, the site-packages folder in the user's roaming profile does not get added to the interpreter's path.  That's due to specific logic in site.py.  This can result in just-installed packages being invisible in the session that did the install but visible in subsequent runs.  Easy enough to work around once you know what is happening but a source of puzzlement for new users.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#81
