### ISSUE TITLE
New-style class memory leak

### ISSUE THREAD

**Issue by grooya** [IronLanguages/main#1426]
New style class objects are holding C# objects that are set as variable. Here is examples of inheritance when using old-style and new-style classes that produce the same result but in first case there is no memory leak while in the second case C# objects are not collected even if garbage collection is forced.
1. Old-style:

```
class Test:
    def __init__(self, variable):
        self.variable = variable

class DerivedTest(Test):
    def __init__(self, *args):
        Test.__init__(self, *args)

testObj = DerivedTest(Variable)
result = testObj.variable.Variable
```
1. New-style:

```
class Test(object):
    def __init__(self, variable):
        self.variable = variable

class DerivedTest(Test):
    def __init__(self, *args):
        super(DerivedTest, self).__init__(*args)

testObj = DerivedTest(Variable)
result = testObj.variable.Variable
```

Note that Variable is set via SetVariable method by instantiating C# Data class.
After running the first script, there are no Data objects in memory, while the second script keeps Data object and it won't release it.

Also, I have performed some measurements when executing this script 10 000 times and got the following results:

Old-style:
Total memory consumption after script execution: 484KB
Total execution time: 231.6ms

New-style:
Total memory consumption after script execution:  1.1MB
Total execution time: 360.6ms

Here is the test console application which presents this issue: [PythonTest.zip](https://github.com/IronLanguages/main/files/485293/PythonTest.zip)

**Comment by simplicbe** [comment]
That is very interesting and may explain some issues we had with IronPython in the past. I'll take a close look at this today. Thanks for reporting it with all details!

**Comment by vukoje** [comment]
@simplicbe it took 2 weeks and 3 guys to pinpoint this issue we are having in production :smile: . I hope this will make a big difference.

**Comment by simplicbe** [comment]
@grooya that is a very interesting behaviour. Because not all `Data` instances are kept in memory, but a few. The GC root seems to be the `PythonContext`.

**Comment by grooya** [comment]
I have used dotMemory to track retain graph and got following:

Old style before Data object got collected:
![oldstyle](https://cloud.githubusercontent.com/assets/22348228/18784707/0ded38e2-8194-11e6-8f89-7a3676b4d946.PNG)

New style after all scripts are executed:
![newstyle](https://cloud.githubusercontent.com/assets/22348228/18784726/41168994-8194-11e6-8e36-e28a1e46140e.PNG)

This maybe useful to find part of code which unnecessary holds C# objects even if script execution is done. I hope this could be fixed because "few" instances are causing problems when ironpython is used as part of Web application which execution "never ends" (application pool restart could only release retained memory) .

**Comment by simplicbe** [comment]
@grooya yep, same result with Teleriks Just Trace :) Thanks for sharing!

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#83
