### ISSUE TITLE
IronPython causes aspect oriented programming interceptor to fail

### ISSUE THREAD

**Issue by ch-hristov** [IronLanguages/main#1433]
I have a class exposed to ironpython. 

I have a C# class exposed to ironpython. My c# class implements `IDynamicMetaObjectProvider`

I need it to do some AoP based work, so I expect that when IronPython calls a method of my exposed C# class I would be able to do some call interception. However, when a call happens it seems that the system cannot recognize that it is a method being invoked and instead it thinks that a property has been 'get'-ed 
so it invokes 

`public override DynamicMetaObject BindGetMember(GetMemberBinder binder)`

instead of 

 `public override DynamicMetaObject BindInvokeMember(InvokeMemberBinder binder, DynamicMetaObject[] args)`

I don't know if the call to BindGetMember is normal, but I'm sure that I must get a call to BidnInvokeMember.

Is there a way to retrieve the normal binder, and get all the benefits of the ironpython binder?

**Comment by slide** [comment]
If you have a question, please use the mailing list. This is for bug reports.
