### ISSUE TITLE
Triage test_type_causing_load_exception in test_reachtype.py to see if we need to file a bug on Mono

### ISSUE THREAD

**Issue by slide** [IronLanguages/main#1440]
There are three issues currently:
1. The following code doesn't throw an ImportError

``` python
try:
    from PossibleLoadException import B
    AssertUnreachable()
except ImportError:
    pass
```
1. The AttributeError for the PossibleLoadException.B doesn't raise an AttributeError
2. The AreEqual(B, 10) is not correct

**Comment by slozier** [comment]
I think this one boils down to the following program:

```
using System.Reflection;

public class Program
{
    public static void Main(string[] args)
    {
        var x = Assembly.Load(new AssemblyName("rowantest.loadexception"));
        var y = x.GetType("PossibleLoadException.B");
        System.Diagnostics.Debug.Assert(y == null);
    }
}
```

throws in Mono, works in .NET.

**Comment by slozier** [comment]
Although I don't see how the type B still gets created if Mono throws...

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#86
