### ISSUE TITLE
Does this replace pythonnet?

### ISSUE THREAD

**Issue by Lisa-V-Sau** [IronLanguages/main#1442]
Hi, 

This is more a question than an issue. 

I actually require pythonnet, though I am having trouble installing it as there are some dependencies which I can not resolve in this place and time. 

I came across IronPython and was wondering whether it would work as installing pythonnet and what are the difference or similarities?

Hope someone can answer my questions. 

Thanks, 
Lisa

**Comment by simplicbe** [comment]
The difference is, that IronPython is completly written in c# and bases on the .net framework. PythonNet (afaics) bases on CPython and works with interops.

What do you mean with _... whether it would work as installing pythonnet ..._?

**Comment by simplicbe** [comment]
Additional: here you find all information: http://pythonnet.github.io/

e.g.: 

> This approach allows you to use use CLR services and continue to use existing Python code and C-based extensions while maintaining native execution speeds for Python code. If you are interested in a pure managed-code implementation of the Python language, you should check out the IronPython project, which is in active development.

If you have more questions, just join us on gitter or use the mailing list. Thank you for your question!

**Comment by Lisa-V-Sau** [comment]
Hi Simplicbe, 

I should of been more specific with my question. 

Basically I am in need of a .Net Bridge to load a library. This is for work. 

I've been told to install pythonnet though I am having failures with it as its unable to build the wheel. For some reason. 

Im trying alternatives, so my question is whether IronPython serve that purpose of a .Net Bridge?

Thanks, 
Lisa

**Comment by simplicbe** [comment]
@karbon62 even better, since IronPytohn is written in .net you don't need any bridge and can natively integrate it into your application. for example this is maybe interesting for you https://github.com/simplic-systems/simplic-dlr as an integration sample.

**Comment by Lisa-V-Sau** [comment]
Thats fantastic thanks for the info @simplicbe!
