### ISSUE TITLE
io.open inside of paren_expr allows file to remain open

### ISSUE THREAD

**Issue by slide** [IronLanguages/main#1446]
This is based on an install of zeroconf using setuptools:

Run the following:

``` python
#!/usr/bin/env python
from __future__ import absolute_import, division, print_function

from io import open

from os.path import abspath, dirname, join

PROJECT_ROOT = abspath(dirname(__file__))

version = (
    [l for l in open(join(PROJECT_ROOT, 'file.py')) if '__version__' in l][0]
    .split('=')[-1]
    .strip().strip('\'"')
)

print('version = {}'.format(version))
raw_input('Press Enter: ')
```

Save this to the same directory as file.py

``` python
__version__ = '1.2.4'
```

If you use something like Process Monitor and run it with CPython, you see that the file.py is closed before you press enter, but with IronPython, file.py remains open until the process exits.

This causes issues with installing some packages as they do this in their code to get the current version of the package (zeroconf is one such package).

**Comment by slozier** [comment]
I initially thought this might be a GC issue, but it looks the file isn't closed if you force a GC. I guess something is still holding a reference to it even after it shouldn't be.

**Comment by slide** [comment]
Either that or the semantics of the scope are not correct.

**Comment by kunom** [comment]
Please note that list comprehensions do not have their own scope in Python2:

```
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> [i for i in range(3)]
[0, 1, 2]
>>> i
2
```

```
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> [i for i in range(3)]
[0, 1, 2]
>>> i
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'i' is not defined
```

**Comment by simplicbe** [comment]
@kunom is this already an issue in the ip3 repository?

**Comment by kunom** [comment]
@simplicbe ip3 is not on my radar, therefore I don't know. I just dealt with that topic in #1199, and I think you could look at the implementation of dict and set comprehensions which have their own scope even in Python2.

**Comment by slozier** [comment]
This isn't specific to `io.open`, I'm guessing it applies to pretty much any `IDisposable`. Here's a minimal test case:

```
[l for l in open('somefile')]
raw_input('Press Enter: ')
```

**Comment by slide** [comment]
Yes, I agree.

**Comment by kunom** [comment]
I disagree. What we observe in such patterns is a) the scope leak of the list comprehension loop variabe, and b) the non-determism of the .NET garbage collector compared to the CPython reference counted collector.

Such Python code is usually considered a bad programming style. Better would be to use the `with` keyword for explicit and controlled resource deallocation.

**Comment by slozier** [comment]
@kunom a) The loop variable is a string so that can't be what's keeping the file object alive. b) If you insert a forced garbage collection in between the list comprehension and the raw_input the file still remains open:

```
x = open("somefile")
[l for l in x]
del l
del x

import System
System.GC.Collect()
System.GC.WaitForPendingFinalizers()
System.GC.Collect()

# the file should be closed at this point but it isn't

raw_input('')
```

I agree it's bad programming style, but that's a separate issue...

**Comment by kunom** [comment]
Excuse me for not reading correctly.

The Visual Studio Debugger tells that the PythonFile object is still rooted by a local variable of type object[], where the 5th item is a KeyValuePair struct where the file object is the key.

![image](https://cloud.githubusercontent.com/assets/1832956/18965440/8d369f4c-867d-11e6-800e-f3ae5f72bb7a.png)

**Comment by slide** [comment]
Correct, it's a temp variable created in the expression tree to track an enumerator for the loop
