### ISSUE TITLE
Tutorial files not run?

### ISSUE THREAD

**Issue by tumagonx** [IronLanguages/main#1463]
Sorry for possible noob question. I only experience CPython before.

I tried install IPy 2.7.6 then run calculator.py and winforms.py from tutorial subdirectory

calculator.py: complaint not found: Windows.System.Controls (I assume this is Silverlight App and need the sdk?)
I tried solve put the required assemblies from SL SDK and add:
clr.AddReferenceByPartialName("System.Windows.Controls") 
but then when I run it, IPy silently quit

winforms.py: Silently quit.

wfdemo.py: works fine

Tested on XP and W10

**Comment by slide** [comment]
Please use the mailing list for questions. The tutorials are something that still need attention after the revival of IronPython.
