### ISSUE TITLE
enable -X:FullFrames by default?

### ISSUE THREAD

**Issue by Samureus** [IronLanguages/main#1469]
Hi, first of all congratulations on the new 2.7.7 RC, but if I have user installed pip packages, it shows a lot of warnings like this one in Ubuntu 16.04:

```
Error processing line 1 of /home/samo/.local/lib/python2.7/site-packages/backports.functools_lru_cache-1.3-py3.5-nspkg.pth:

  Traceback (most recent call last):
    File "/home/samo/Dev/IronPython-2.7.7rc0/Lib/site.py", line 152, in addpackage
      exec line
    File "<string>", line 1, in <module>
  AttributeError: 'module' object has no attribute '_getframe'

Remainder of file ignored
```

The message dissapears if I pass the `-X:FullFrames` flag to ipy.exe, of course. I was wondering what's the tradeoff of enabling this flag on by default.

**Comment by slide** [comment]
There is some discussion on this already at #1072 , we'll definitely look into it.
