### ISSUE TITLE
Change console color on *nix

### ISSUE THREAD

**Issue by michaelblyons** [IronLanguages/main#1471]
I'm on OSX, and I have a light theme for my terminal emulator. Is there a way to use a dark color for the text output? The `-X:ColorfulConsole` flag does not seem to have any effect, either.

I have a crummy workaround wherein I alias the `ipy` command to darken and restore the terminal color. But after I leave the IronPython console or my command finishes running, it's hard to read again.

``` sh
#!/bin/sh

# Set iTerm2 to a dark theme
echo "\033]1337;SetProfile=IronPython\a"

EXE_PATH=$HOME/various/paths/ironlangs/bin/Debug
mono $EXE_PATH/ipy.exe -D -X:TabCompletion -X:ColorfulConsole "$@"

# Revert iTerm2 to the default theme
echo "\033]1337;SetProfile=\a"
```

Ideally, IronPython would respect my default colors and my color map.

**Comment by slide** [comment]
I agree, IronPython should use your console colors. I don't know that any of the community members have OSx to test on, but we'll see what we can do.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#26
