### ISSUE TITLE
RC 2.7.7 rc0 regression

### ISSUE THREAD

**Issue by ita1024** [IronLanguages/main#1474]
With the following piece of code:

``` python
try:
        import winreg
except ImportError:
        import _winreg as winreg
key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, "SOFTWARE\\Wow6432node\\Microsoft\\VisualStudio\\14.0\\Setup\\VC")
path,type = winreg.QueryValueEx(key, 'ProductDir')
print(repr(path))
print(str(path))
```

The version rc0 outputs this:

```
$ /C/Program\ Files\ \(x86\)/IronPython\ 2.7/ipy64.exe test.py
u'\u3a43\u505c\u6f72\u7267\u6d61\u4620\u6c69\u7365\u2820\u3878\u2936\u4d5c\u6369\u6f72\u6f73\u7466\u5620\u7369\u6175\u206c\u7453\u6475\u6f69\u3120\u2e34\u5c30\u4356\\'
???????????????????????????\
```

By comparison, here is the output on Python (the version does not really matter). I believe that the old IronPython from 2 years ago also worked properly:

```
$ /C/Python34/python.exe test.py
'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
```

Correction: i have not tested this snippet with the previous release because i had problems running it.

**Comment by paweljasinski** [comment]
works fine under ipy 2.7.5

**Comment by slozier** [comment]
@paweljasinski We replaced the .NET call with a PInvoke because of performance issues. I will look into it this evening.

**Comment by slide** [comment]
Maybe a CharSet issue for the P/Invoke method?

**Comment by slozier** [comment]
Most likely.
