### ISSUE TITLE
test_memory_20 failing with -X:Frames

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1480]
When running the full test suite with -X:Frames to see what sort of perf hit we would get if frames were on by default I noticed that `test_cp26005` in `test_memory_20` fails. Seems like it could be a memory leak.

**Comment by simplicbe** [comment]
Thanks, I will reproduce the issue and profile it.

**Comment by slide** [comment]
Related to #1072

**Comment by slozier** [comment]
Looks like we have an issue with removing stuff from the frame stack:

``` Python
import inspect

def test_cp26005():
    def coroutine():
        just_numbers = range(1,100000)
        def inner_method():
            return just_numbers
        print len(inspect.stack())        
        yield None

    for j in xrange(3):
        crt = coroutine()
        crt.next()

test_cp26005()
```

Outputs in IronPython (with -X:Frames):

> 3
> 4
> 5

and in CPython:

> 3
> 3
> 3

**Comment by slozier** [comment]
It seems to be caused by generators that are not fully consumed (which is what the [original issue](https://ironpython.codeplex.com/workitem/26005)) was about. Here's a simpler example.

``` Python
import inspect

def test_issue1480():
    def coroutine():
        yield None

    for j in xrange(3):
        crt = coroutine()
        crt.next()
        print len(inspect.stack())

test_issue1480()
```
