### ISSUE TITLE
IronPython 2.7.6 makes Rhino3D crash

### ISSUE THREAD

**Issue by deviezeviking** [IronLanguages/main#1481]
Hi all,

Not sure if this is a IronPython problem, or rather a Rhino3D problem, but when using IronPython 2.7.6 in combination with Rhino3D, Rhino3D crashes.

This happens in the following situation.
Rhino ships with IronPython 2.7.0 beta, which raises all sorts of error when using dictionaries. This is easily fixed by making Rhino use a final release of IronPython, for example 2.7.5 final. 

However, as said, for whatever reason the latest IronPython 2.7.6 makes Rhino crash, as soon as any Python script is executed.

Any insight in the cause of this problem would be helpful.

Thanks!

**Comment by slozier** [comment]
I tried it over here and it worked, maybe you can give more details about how you set it up? Here's what I did:
- Download/install Rhino 5 evaluation
- Go in C:\Program Files (x86)\Rhinoceros 5\Plug-ins\IronPython and delete Lib, IronPython.dll, IronPython.Modules.dll, Microsoft.Dynamic, Microsoft.Scripting.
- Put the new versions of the files in the same folder as above
- Start Rhino, go in Tools->PythonScript->Run and then I ran the HelloPython.py sample

**Comment by slide** [comment]
Please reopen on IronLanguages/ironpython2 if this is still an issue.
