### ISSUE TITLE
hmac.py can't find operator._compare_digest

### ISSUE THREAD

**Issue by Jerhaad** [IronLanguages/main#1498]
New line added from CPython lib to import compare_digest from operator, but IPY 2.7.6 doesn't have that function in operator.

Nor does hmac really use it.

**Comment by slide** [comment]
I thought I added this, I'll double check my local repo

**Comment by slide** [comment]
This is fixed already in 2.7.7 RC0, see #1448

**Comment by michaelblyons** [comment]
In case anyone was curious, the specific file in the merge is [`.../IronPython.Modules/operator.cs`.][1] Jerhaad is correct, so far as I understand it: `hmac.py` doesn't seem to use the `_compare_digest` function at all, and commenting out the `import` line in 2.7.6 seems to work fine. Hopefully this doesn't open up a vulnerability to timing attacks. 😉 

[1]: https://github.com/IronLanguages/main/pull/1448/files#diff-b19622415b845b10fb1e564e58c4df73
