### ISSUE TITLE
`LocalsDictionary` bugs

### ISSUE THREAD

**Issue by kunom** [IronLanguages/main#1504]
The `LocalsDictionary` class that is used as storage provider for the dict instance returned in `frame.f_locals` is broken in at least two aspects (compared to CPython):
- Enumeration includes unintialized locals
- Key containment checks do not work, not even for initialized locals

Test code:

``` python
import sys
def f():
    aa = 3
def thandler(frm, evt, pl):
    print frm.f_code.co_name, evt, frm.f_locals, 'aa' in frm.f_locals
    return thandler
sys.settrace(thandler)
f()
sys.settrace(None)
```

CPython output:

```
f call {} False
f line {} False
f return {'aa': 3} True
```

IronPython output:

```
f call {'aa': None} False
f line {'aa': None} False
f return {'aa': 3} False
```

Found while investigating #1296.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#90
