### ISSUE TITLE
Tracing reports incorrect line numbers for generator functions

### ISSUE THREAD

**Issue by kunom** [IronLanguages/main#1518]
```python
import sys
def g():
    aa = 4
    yield 3
def thandler(frm, evt, pl):
    print frm.f_code.co_name, frm.f_lineno, evt
    return thandler
sys.settrace(thandler)
list(g())
sys.settrace(None)
```

CPython output:
```
g 2 call
g 3 line
g 4 line
g 4 return
g 4 call
g 4 return
```

IronPython output (note the last two line numbers):
```
g 2 call
g 3 line
g 4 line
g 4 return
g 2 call
g 2 return
```

**Comment by simplicbe** [comment]
@kunom thanks for reporting that. Do you have an idea, why this is happens?

**Comment by kunom** [comment]
No, this needs debugging. It is like #1504 a by-product of my investigations of #1296.

My gut feeling is that debugging code generation and particularly the `DebuggableLambdaBuilder` class is not (yet) at the same maturity level as other parts of the IronPython code base. Compared to CPython, tracing is implemented in an extremely complicated and convoluted way.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#94
