### ISSUE TITLE
implement the _tkinter module in the IronPython core

### ISSUE THREAD

**Issue by mdengusiak** [IronLanguages/main#1537]
Would be possible to implement the _tkinter module in the IronPython core?
or there is any way to get it working?

**Comment by slide** [comment]
Would you want interfacing with Tcl/Tk, or just a wrapper around another GUI library?

**Comment by mdengusiak** [comment]
I want to be able import Turtle module so can show young people and children that programming is fun and we can combine simple and more complex scripts from same environment which will be Dynamo BIM for Revit.

**Comment by mdengusiak** [comment]
@slide What do you think about getting Tkinter?

**Comment by slide** [comment]
I think it would probably happen on the ironpython3 release tree instead of here, but it wouldn't be soon.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#80
