### ISSUE TITLE
ipc.exe hangs on bad input

### ISSUE THREAD

**Issue by andygraham** [IronLanguages/main#1546]
Hopefully I'm not wasting your time again :(

If you run ipyc.exe with a bad option or missing filename to compile, or if there is a syntax, indentation or other error during compilation the console from which it is run reports an unhandled exception stack trace and the "IronPythonCompiler has stopped working" dialog is shown and has to be manually closed.

Also see the additional comment below

**Comment by slide** [comment]
Thanks for filing this, I noticed this same thing and keep forgetting to file an issue on it.

**Comment by andygraham** [comment]
I just noticed another minor feature for when you dig into this.

If by accident :) you specify say `/out:fred.py` as the exe target it is correctly compiled to `fred.exe` but the console, or whatever is reading standard output, sees `Saved to fred.py` giving you a heartstopping moment until you check all is well :)

**Comment by andygraham** [comment]
There's a typo in the message box in ipc.exe  Main().
`MessageBox.Show(string.Format("Error occured: {0}", message), "Error", MessageBoxButtons.OK, MessageBoxIcon.Hand)`

`occured` should be `occurred`

**Comment by slide** [comment]
If you feel up to it, you are welcome to create pull requests for fixing things. I will get to them, but if you want to be involved in the process more, a PR would be more than welcome :-)

**Comment by andygraham** [comment]
I would have no idea where to start! Aged 70 and retired I can still write complex reflective C# code that pokes deep into the CLR and P/Invoke but I find all this NuGet, Choclatey and GitHub webby based stuff totally alien :(

**Comment by slozier** [comment]
@andygraham For something simple like a typo it's easy to do a PR directly from github. I believe that's how I did my first PR on github. Find the file you want to edit (e.g. https://github.com/IronLanguages/main/blob/ipy-2.7-maint/Languages/IronPython/IronPythonCompiler/Config.cs#L28), click on the little pencil at the top right of the editor then you can edit the file and do the PR.

**Comment by andygraham** [comment]
"click on the little pencil at the top right" is about the limit of my capability and understanding but I did it and made my very own very slight contribution to IronPython! Finding the right file was difficult though.
