### ISSUE TITLE
Provide DocString for a .NET class

### ISSUE THREAD

**Issue by lafrank** [IronLanguages/main#1553]
Is there a supported way for a .NET class and its members to provide a DocString that is returned in Python environment by `__doc__`  ?

**Comment by slide** [comment]
Please use the mailing list for questions. There is a DocumentationAttribute available that can be used for this purpose

**Comment by lafrank** [comment]
Thanks. Actually found DocumentationAttribute, just can't use it. Will post my question on the mailing list.

**Comment by lafrank** [comment]
My problem is that I can't use DocumentationAttribute for providing
DocString. I documented the issue in details on this MSDN forum
<https://social.msdn.microsoft.com/Forums/en-US/3749d379-2b27-421d-8108-01edd42fd550/limited-class-visibility?forum=csharpgeneral>,
could someone please have a look what I am missing here ?
