### ISSUE TITLE
2.7.7 .msi installer falsely detects newer version

### ISSUE THREAD

**Issue by tjhb** [IronLanguages/main#1555]
Attempting to install IronPython 2.7.7 from its .msi installer over incumbent version 2.7.6.3 throws error "a later version of IronPython 2.7.7 is already installed".

(Not true.)

**Comment by slide** [comment]
This is something that can't be fixed because of the way the version for the msi was generated in the past.

**Comment by tjhb** [comment]
Thanks. Removing 2.7.6.3 then installing 2.7.7 works fine.
And thanks for all your work. So happy that IronPython is in good hands.
