### ISSUE TITLE
“PythonCompilerTask” failed on 2.7.7 while success on 2.7.5

### ISSUE THREAD

**Issue by bnuzhouwei** [IronLanguages/main#1557]
“PythonCompilerTask” failed on 2.7.7 while success on 2.7.5。
System.NullReferenceException: 
   on IronPython.Runtime.PythonTuple.GetHashCode()
   on System.Collections.Generic.ObjectEqualityComparer`1.GetHashCode(T obj)
   on System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   on System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   on Microsoft.Scripting.Generation.ToDiskRewriter.VisitConstant(ConstantExpression node)
   on System.Linq.Expressions.ConstantExpression.Accept(ExpressionVisitor visitor)
   on System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   on System.Linq.Expressions.ExpressionVisitor.VisitUnary(UnaryExpression node)
   on System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   on System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   on System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   on System.Linq.Expressions.ExpressionVisitor.VisitNewArray(NewArrayExpression node)
   on System.Linq.Expressions.NewArrayExpression.Accept(ExpressionVisitor visitor)
   on System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   on System.Linq.Expressions.ExpressionVisitor.VisitArguments(IArgumentProvider nodes)
   on System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   on System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   on System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   on Microsoft.Scripting.Generation.ToDiskRewriter.VisitLambda[T](Expression`1 node)
   on System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   on System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   on IronPython.Compiler.PythonSavableScriptCode.CompileForSave(TypeGen typeGen)
   on Microsoft.Scripting.SavableScriptCode.SaveToAssembly(String assemblyName, SavableScriptCode[] codes)
   on IronPython.Runtime.ClrModule.CompileModules(CodeContext context, String assemblyName, IDictionary`2 kwArgs, String[] filenames)
   on ICSharpCode.Python.Build.Tasks.PythonCompiler.Compile()
   on ICSharpCode.Python.Build.Tasks.PythonCompilerTask.Execute()
   on Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   on Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() (MSB4018)

**Comment by slide** [comment]
Can you please give some more information on how to reproduce this?

**Comment by slide** [comment]
FYI, PythonCompilerTask is part of the the SharpDevelop code base, not IronPython.

**Comment by bnuzhouwei** [comment]
Thanks, I wan't to use sharpdevelop to build a dll of IronPython.StdLib. Finally, I have done this using pyc.

```python
gb = []
def fun( path ):    
    for fn in glob.glob( path + os.sep + '*' ):
        if os.path.isdir(fn):
            fun(fn)
        elif fn.endswith(".py"):
            gb.append(fn)
fun("./Lib")

gb.append("/out:IronPython.StdLib")    

print len(gb)
print ["/target:dll",]+gb
pyc.Main(["/target:dll"]+gb)
```
