### ISSUE TITLE
IronPython: No module named json

### ISSUE THREAD

**Issue by pirovorster** [IronLanguages/main#1560]
I have IronPython installed

My python file looks like this:

```
import sys
print(sys.version)
import json

```
The code that runs it:
```

var p = Python.CreateEngine();
var scope = p.CreateScope();
p.ExecuteFile("Test.py", scope);
```
It prints out: "2.7.7 (IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (32-bit))" But then fails with the exception: No module named json

As I understand the json module should be included in this version of IronPython.

Why do I get this error?

**Comment by slide** [comment]
Please use the mailing list for questions. You need to set the search path for the engine to include the IPy stdlib directory.

**Comment by pirovorster** [comment]
Thank you
