### ISSUE TITLE
Console streams not working in binary mode

### ISSUE THREAD

**Issue by oblaise** [IronLanguages/main#1561]
Dear All,

While testing a sample from Mozilla I discovered the following issue with IronPython: it doesn't seems to support correctly file IO on stdin and stdout when the streams are in binary mode. The same sample running on standard python (2.7.13) was working correctly (On Windows server 2012 for both tests).

The data has the following format: 4 byte representing the length followed by a string UTF-8 encoded of the length read before. This is done using following function:
```
def getMessage():
    rawLength = sys.stdin.read(4)
    if len(rawLength) == 0:
        sys.exit(0)
    messageLength = struct.unpack('@I', rawLength)[0]
    message = sys.stdin.read(messageLength)
    return json.loads(message)
```
As soon as the length of the string>=128 the rawLength returnes by `sys.stdin.read(4)` is wrong.

Similar issue appends for writing message using the same structure.

Kind regards,
--ob

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#75
