### ISSUE TITLE
TypeError: RawIOBase: IOBase is not an acceptable base type when import tempfile

### ISSUE THREAD

**Issue by alexey-tyulkin** [IronLanguages/main#1563]
`IronPython 2.7.7 (2.7.7.0) on .NET 4.0.30319.42000 (64-bit)`
`Type "help", "copyright", "credits" or "license" for more information.`
`>>> import tempfile`
`Traceback (most recent call last):`
`TypeError: RawIOBase: IOBase is not an acceptable base type`

**Comment by slozier** [comment]
This is working fine for me. Can you provide details on your setup?

**Comment by alexey-tyulkin** [comment]
Thanks
I can not reproduce on fresh release archive 
Will review my setup
