### ISSUE TITLE
IronPython does not support calling Rx.NET extension methods

### ISSUE THREAD

**Issue by glopesdev** [IronLanguages/main#1564]
Can someone please explain me this really weird observation?

I've been trying to call Rx extension methods from inside IronPython and it is turning out to be simply impossible. I've boiled it down to this simple example:

```python
import clr
clr.AddReference("System.Core")
from System.Linq import Enumerable

def process(value):
  return Enumerable.Select(value, lambda x:x)
```

In this case we start with normal LINQ. If I call the ```process``` function from my hosting environment with an array or any other ```IEnumerable``` object, it works totally fine.

So then I tried to simply replace the references to use the ```Observable``` extension methods like so:

```python
import clr
clr.AddReference("System.Reactive.Linq")
from System.Reactive.Linq import Observable

def process(value):
  return Observable.Select(value, lambda x:x)
```

In this case, if I call the ```process``` function with an ```IObservable``` object, the call crashes with an ugly error message:

```expected IObservable[object], got Select[int, int]```

Has anyone hit upon something like this? Have I missed something? Is there some special case hack to make ```Enumerable``` work with lambda delegates that ```Observable``` is missing? I have to admit I'm completely baffled here.

By the way, just as a sanity check, the following example works just fine:

```python
import clr
clr.AddReference("System.Reactive.Linq")
from System.Reactive.Linq import Observable

def process(value):
  return Observable.Sum(value)
```

I wanted to leave it out there just to make it clear that the problem really is in the method call to ```Observable.Select```.

**Comment by glopesdev** [comment]
More examples that seem to point out that this is some issue with method call resolution in IronPython:

```python
import clr
clr.AddReference("System.Reactive.Linq")
from System.Reactive.Linq import Observable

def process(value):
  return Observable.Count(value, lambda x:True)
```

This does not work (same as above). But this does:

```python
import clr
clr.AddReference("System.Reactive.Linq")
from System.Reactive.Linq import Observable

def process(value):
  return Observable.Count[int](value, lambda x:True)
```

Only difference was that the type of the generic method call was specified explicitly. Of course, then the script does not work for any input type.

Interestingly, even this fix fails to correct the behavior with ```Select```. For example:

```python
import clr
clr.AddReference("System.Reactive.Linq")
from System.Reactive.Linq import Observable

def process(value):
  return Observable.Select[int,int](value, lambda x:x)
```

This case still crashes, but now the error message changes to:

```Multiple targets could match: Select(IObservable[int], Func[int, int]), Select(IObservable[int], Func[int, int, int])```

These examples I think raise a red flag that there is something wrong with method call resolution and type inference when lambdas are involved. I've also been able to reproduce the same behavior with generic method stubs that I've implemented myself. They crash exactly in the same way as Rx methods so in fact this issue is more general than just with Rx.

Indeed, the question that can now be asked is actually why do the methods from the ```Enumerable``` class work at all?

**Comment by glopesdev** [comment]
By the way, here is a simple hosting test setup to reproduce the issue:

```c#
using IronPython.Hosting;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reactive.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TestPython
{
    class Program
    {
        static void Main(string[] args)
        {
            var engine = Python.CreateEngine();
            var scope = engine.CreateScope();
            var source = engine.CreateScriptSourceFromString(@"
import clr
clr.AddReference(""System.Reactive.Linq"")
from System.Reactive.Linq import Observable

def process(value):
  return Observable.Count(value)");
            source.Execute(scope);

            var process = scope.GetVariable("process");
            var input = Observable.Return(1);
            var output = process(input);
            var result = Observable.Wait(output);
            Console.WriteLine(result);
        }
    }
}
```

You can replace the script code with different method call variants and see what happens.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#73
