### ISSUE TITLE
Question: How can I use a python library in a C#(mono) app?

### ISSUE THREAD

**Issue by devkhan** [IronLanguages/main#1565]
I want to develop a cross-platform app based on mono or .NET core runtime, but since I want to use a python library(namely `youtube-dl`) in it. Since, I need to use a python package in a C# app, the native CPython implementation can't be used. Is it possible using IronPython?

PS: The python library is 2.7 compatible.

**Comment by slide** [comment]
Please use the mailing list for questions. Does youtube-dl require native libraries?

**Comment by devkhan** [comment]
Sure, should I ask this on Gitter?

And no, it doesn't require any native extensions.

**Comment by slide** [comment]
Gitter would be fine too. If it doesn't require native extensions, it should work fine with IronPython. You can use pip to install it, just pass -X:Frames to ipy.exe.
