### ISSUE TITLE
IronPython issue installing PIP

### ISSUE THREAD

**Issue by ahmedbodi** [IronLanguages/main#1570]
This is the error i get when trying to install pip. running on Windows 10. Latest Release 2.7.7. 64 Bit Machine
```
C:\Program Files (x86)\IronPython 2.7>"C:\\Program Files (x86)\\IronPython 2.7\\ipy64.exe" -X:Frames  -m ensurepip
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools

Process is terminated due to StackOverflowException.```

**Comment by slozier** [comment]
I confirm that running `ensurepip` with `ipy64` gives a `StackOverflowException`.

As a workaround I believe you can run it with the 32-bit `ipy` and it will work (and do the same thing). Note that you need to run it with an admin console since it installs files in your program files folder.

**Comment by ahmedbodi** [comment]
with ipy it gives the same error

**Comment by ahmedbodi** [comment]
```
C:\Program Files (x86)\IronPython 2.7>ipy.exe -X:Frames -m ensurepip
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools

Process is terminated due to StackOverflowException.

C:\Program Files (x86)\IronPython 2.7>
```

**Comment by slozier** [comment]
I managed to reproduce with the following (while running `ipy64` - still works fine for me in 32-bit). Although I can't seem to get it to fail when the debugger is attached.
```
import mimetypes
print(mimetypes.guess_type(r"https://docs.python.org/2/library/mimetypes.html"))
```

Another possible workaround you could try is to try `ipy.exe -X:Frames -X:Debug -m ensurepip`.

**Comment by slide** [comment]
-X:ExceptionDetail might be useful too

**Comment by slide** [comment]
mimetypes does a registry lookup on Windows I think, maybe the issue is there.

**Comment by slozier** [comment]
@slide I also wanted to blame the registry since it was failing on a throw from there, but after watering down the code the following is giving me a `StackOverflowException`:
```Python
def raise_exception():
    raise Exception()

class contextmanager(object):
    def __enter__(self):
        return None
    def __exit__(self, *args):
        pass

for _ in xrange(50):
    try:
        with contextmanager():
            raise_exception()
    except Exception:
        pass
```

`-X:ExceptionDetail` gives nothing. I'm guessing it's because you can't recover from a `StackOverflowException`.

**Comment by jump3r34** [comment]
I got the same error and ran it through debug on VS2015 Ultimate (Or Pro - I can't remember)

To view this debug error - someone may want to paste it into a text editor as it is wrapping lines right here.

`'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Symbols loaded.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\IronPython27\ipy.exe'. Cannot find or open the PDB file.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Dynamic\v4.0_1.1.2.22__7f709c5b713576e1\Microsoft.Dynamic.dll'. Cannot find or open the PDB file.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Microsoft.Scripting\v4.0_1.1.2.22__7f709c5b713576e1\Microsoft.Scripting.dll'. Cannot find or open the PDB file.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Core\v4.0_4.0.0.0__b77a5c561934e089\System.Core.dll'. Symbols loaded.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System\v4.0_4.0.0.0__b77a5c561934e089\System.dll'. Symbols loaded.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Configuration\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Configuration.dll'. Symbols loaded.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Xml\v4.0_4.0.0.0__b77a5c561934e089\System.Xml.dll'. Symbols loaded.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\IronPython\v4.0_2.7.7.0__7f709c5b713576e1\IronPython.dll'. Cannot find or open the PDB file.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\System.Numerics\v4.0_4.0.0.0__b77a5c561934e089\System.Numerics.dll'. Symbols loaded.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\IronPython.Modules\v4.0_2.7.7.0__7f709c5b713576e1\IronPython.Modules.dll'. Cannot find or open the PDB file.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\IronPython27\DLLs\IronPython.SQLite.dll'. Cannot find or open the PDB file.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\IronPython27\DLLs\IronPython.Wpf.dll'. Cannot find or open the PDB file.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'Snippets.scripting'. 
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'IronPython.Modules.DynamicAssembly'. 
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'Snippets'. `

**Comment by slozier** [comment]
@jump3r34 I'm not seeing an error in there, just info about your assemblies loading.

Note that you can use triple ticks to preserve line endings, for example, the following
\`\`\`
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Symbols loaded.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\IronPython27\ipy.exe'. Cannot find or open the PDB file.
...
\`\`\`
would give
```
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_32\mscorlib\v4.0_4.0.0.0__b77a5c561934e089\mscorlib.dll'. Symbols loaded.
'ipy.exe' (CLR v4.0.30319: ipy.exe): Loaded 'C:\IronPython27\ipy.exe'. Cannot find or open the PDB file.
...
```

**Comment by ahmedbodi** [comment]
Okay now this is weird.

On my laptop, i was using a local account which has administrator privs. however it is also connected to a domain. Just now i've logged into the domain administrator account and tried it and it works fine. Any idea why?

**Comment by jump3r34** [comment]
I didn't have time to mess with IronPython for hours to get it working, sorry guys.

I am proficient enough with C# and Python individually that the headache was not worth the work.  Both of my windows laptops and office machine was having different errors, however, python2.7 and python3.5 and 3.6 work flawlessly on them and my Macbook.  

I was really using it to get a few complicated db functions I had already reflected with SQLalchemy in a WPF app for our sales guys, but I just put it in a django app already.  

I am staying subscribed to this thread because if they ever got Python3 on IronPython - it would make some of the things I do - much much quicker. Also, if I get some time in the next few weeks I am going to actually crack open the VS2015 full debugging environment and find what is throwing that error so it can help a lot of people online.

**Comment by ahmedbodi** [comment]
i now cant install anything because i get a sys_getframe error. ive tried with -X:Frames or X:FullFrames

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#42
