### ISSUE TITLE
Is IronRuby dead?

### ISSUE THREAD

**Issue by abhi18av** [IronLanguages/main#1571]
Hii IronLanguages team:)

I see that in the repo description it's mentioned that it houses `Implementations of Python and Ruby ...` but the main repo is pure python plus I see that some efforts are being made to port this to `python3` whereas `ruby` isn't mentioned at all.

My question is that is there any hope for a tangible alternative to `jRuby` on the `dotNET`?

**Comment by slide** [comment]
It's been moved to its own repository under IronLanguages. This repo is for IronPython 2 and there is a separate repo for IronPython 3. There were some folks interested in IronRuby, but we are not part of any effort to keep it up.
