### ISSUE TITLE
sys.exit behavior not consistent with CPython

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1578]
In CPython (at least on Windows) if `sys.exit` is called with a non-integer value then the value is output to stderr.

In IronPython, non-integer values are not output to stderr. Furthermore it appears that if the argument is a tuple of one element, its value will be extracted from the tuple and used as the exit code.

Reference: https://docs.python.org/2/library/sys.html#sys.exit

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#68
