### ISSUE TITLE
IronPython 2.7.7 - pyc.py doesn't compile to exe/winexe

### ISSUE THREAD

**Issue by damirdev** [IronLanguages/main#1579]
This pull request https://github.com/IronLanguages/main/pull/1528/files break reflection in pyc.py:

C:\dev\src\ch01>"C:\Program Files\IronPython 2.7\ipy.exe" "C:\P
rogram Files\IronPython 2.7\Tools\Scripts\pyc.py" /target:exe /main:funcs.py /ou
t:funcs
Input Files:
Output:
        funcs
Target:
        ConsoleApplication
Platform:
        ILOnly
Machine:
        I386

Compiling...
Traceback (most recent call last):
  File "C:\Program Files\IronPython 2.7\Tools\Scripts\pyc.py", line 332, in <mod
ule>
  File "C:\Program Files\IronPython 2.7\Tools\Scripts\pyc.py", line 327, in Main

  File "C:\Program Files\IronPython 2.7\Tools\Scripts\pyc.py", line 181, in Gene
rateExe
SystemError: Ambiguous match found.

Line 181(C:\Program Files\IronPython 2.7\Tools\Scripts\pyc.py):  
gen.EmitCall(OpCodes.Call, **clr.GetClrType(PythonOps).GetMethod("InitializeModuleEx")**, ())

I'm fixied it with
gen.EmitCall(OpCodes.Call, clr.GetClrType(PythonOps).GetMethod("InitializeModuleEx", (clr.GetClrType(Assembly), clr.GetClrType(str), clr.GetClrType(System.Array[System.String]), clr.GetClrType(System.Boolean))), ())

But I'm beginner in Python & IronPython, and don't know reasons of overloaded method with  Dictionary<string, object> options argument.

Can anyone fix this issue ?

**Comment by slide** [comment]
Pyc.py is deprecated, please use ipyc.exe

**Comment by slozier** [comment]
@slide In that case we should probably remove pyc.py from the release package.

**Comment by slide** [comment]
Agreed

**Comment by damirdev** [comment]
Thanks :)
