### ISSUE TITLE
Installing Sho 2.1 on IronPython 2.7 fails

### ISSUE THREAD

**Issue by axeldomingues** [IronLanguages/main#1582]
After installing the lateste IronPython(2.7.7 released on 2016-12-07) and Sho 2.1, thereafter i launched Sho 2.1 and it did failed with the following error description:
Loading sho...
Traceback (most recent call last):
  File "C:\Program Files (x86)\Sho 2.1\bin\\..\sho\shostarter.py", line 8, in <module>
  File "C:\Program Files (x86)\Sho 2.1\sho\sho.py", line 97, in <module>
  File "C:\Program Files (x86)\Sho 2.1\sho\shoload.py", line 76, in ShoLoadAssemblyFromBinDir
  File "C:\Program Files (x86)\Sho 2.1\sho\shoload.py", line 66, in ShoLoadAssembly
IOError: [Errno 2] Could not load file or assembly 'Microsoft.Dynamic, Version=1.1.0.20, Culture=neutral, PublicKeyToken=7f709c5b713576e1' or one of its dependencies. The system cannot find the file specified.

Note: followed the installation instructions on (https://www.microsoft.com/en-us/research/project/sho-the-net-playground-for-data/)

Any idea how can this problem be fixed?

Thanks in advance for your help.

Regards,

Axel

**Comment by andygraham** [comment]
The version of Microsoft.Dynamic in IronPython 2.7.7 is 1.1.2.22. I think that the only way this would work is if Sho was recompiled against the IronPython 2.7.7 assemblies but I guess you are stuck with IronPython 2.7.6 as I can't see that the Sho source code is available anywhere.

**Comment by axeldomingues** [comment]
Thank you for pointing this out. Indeed it is a problem in Sho that needs to be addressed by Sho team.

Kind Regards,
Axel
