### ISSUE TITLE
Random only generating between 0 and 0.5 in 2.7.7

### ISSUE THREAD

**Issue by kjokay** [IronLanguages/main#1583]
I might be crazy, but going through various tests, I've only been able to generate random numbers between 0 and 0.5 using the random.random() module function in python.

Similar results using the random() function of the IronPython.Modules.PythonRandom.Random class.

Finally, looking at the code in _random.cs, the random() function, the following code never returns a value greater than 0.5 either:

`(((uint)_rnd.Next() >> 5) * 67108864.0 + ((uint)_rnd.Next() >> 6)) * (1.0/9007199254740992.0)`

**Comment by slozier** [comment]
You are not crazy, it's clearly a bug.

`_rnd.Next()` generates a value between 0 and 0x7FFFFFFF while the equation expects values between 0 and 0xFFFFFFFF. That gives a maximum possible value of 0.4999999962747096.

**Comment by slide** [comment]
I'll fix soon

**Comment by johngpayne** [comment]
Is there a way of getting a prebuilt windows DLL version with this fix in?
