### ISSUE TITLE
Selenium WebDriverException when opening a browser in Robot/IronPython

### ISSUE THREAD

**Issue by as-lg** [IronLanguages/main#1585]
I receive the error below using RobotFramework/Selenium2Library with IronPython, however, I don't using Python 27. My Paths are correct as I can execute IEDriverServer anywhere in the cmdline. The issue seems to be related with IP and Selenium2Library.

The executable IEDriverServer.exe needs to be available in the path. Please download from http://selenium-release.storage.googleapis.com/index.html and read up at https://github.com/SeleniumHQ/selenium/wiki/InternetExplorerDriver
close_fds is not supported on Windows platforms if you redirect stdin/stdout/stderr	
FAIL	WebDriverException

Also, there is a thread for this as well:

https://groups.google.com/forum/#!topic/robotframework-users/9MgYfM9cHFI

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#66
