### ISSUE TITLE
error when convery python script to executable file

### ISSUE THREAD

**Issue by hoyeunglee** [IronLanguages/main#1587]
ipy.exe "C:\Program Files (x86)\IronPython 2.7\Tools\Scripts\pyc.py" /main:replaceicecloudappli
cation.py /target:exe
Input Files:
Output:
        replaceicecloudapplication
Target:
        ConsoleApplication
Platform:
        ILOnly
Machine:
        I386

Compiling...
Traceback (most recent call last):
  File "C:\Program Files (x86)\IronPython 2.7\Tools\Scripts\pyc.py", line 332, i
n <module>
  File "C:\Program Files (x86)\IronPython 2.7\Tools\Scripts\pyc.py", line 327, i
n Main
  File "C:\Program Files (x86)\IronPython 2.7\Tools\Scripts\pyc.py", line 181, i
n GenerateExe
SystemError: Ambiguous match
Ambiguous match found.

**Comment by slide** [comment]
Pyc.py is no longer supported, please use ipyc.exe

**Comment by hoyeunglee** [comment]
What is the command to use it to connect convert py script to executable file?

**Comment by slide** [comment]
Sorry, I didn't mean to close the issue.

**Comment by hoyeunglee** [comment]
How to convert script to executable file?

**Comment by slide** [comment]
Usage: ipyc.exe [options] file [file ...]
Options:
    /out:output_file                          Output file name (default is main_file.<extenstion>)
    /target:dll                               Compile only into dll.  Default
    /target:exe                               Generate CONSOLE executable stub for startup in addition to dll.
    /target:winexe                            Generate WINDOWS executable stub for startup in addition to dll.
    /py:<option>                              Allows specifying options that modify the behavior of IronPython (e.g., -X:FullFrames)
    @<file>                                   Specifies a response file to be parsed for input files and command line options (one per line)
    /? /h                                     This message    
EXE/WinEXE specific options:
    /main:main_file.py                        Main file of the project (module to be executed first)
    /platform:x86                             Compile for x86 only
    /platform:x64                             Compile for x64 only
    /embed                                    Embeds the generated DLL as a resource into the executable which is loaded at runtime
    /standalone                               Embeds the IronPython assemblies into the stub executable.
    /mta                                      Set MTAThreadAttribute on Main instead of STAThreadAttribute, only valid for /target:winexe
    /errfmt:msg                               A string that will be used when showing an error occured, {{0}} will be replaced by the exception message
    /win32icon:file.ico                       Sets file.ico as the icon for the executable
Example:
    ipyc.exe /main:Program.py Form.py /target:winexe

**Comment by slide** [comment]
See this file https://github.com/IronLanguages/main/blob/ipy-2.7-maint/Languages/IronPython/IronPythonCompiler/ConsoleOps.cs

**Comment by hoyeunglee** [comment]
no files or valid field defined,

C:\Users\martlee2\Documents\replaceicecloudapplication>ipyc.exe /main:replaceicecloudapplication.py /target:replaceicecloudapplication.exe

C:\Users\martlee2\Documents\replaceicecloudapplication>ipyc.exe /main:C:\Users\m
artlee2\Documents\replaceicecloudapplication\replaceicecloudapplication.py /targ
et:C:\Users\martlee2\Documents\replaceicecloudapplication\replaceicecloudapplica
tion.exe
ERROR: No files or main defined

```
import sys
import clr
import csv
import os
import System
from System import DateTime
import time
    
clr.AddReference("Microsoft.Office.Interop.Word")
import Microsoft.Office.Interop.Word as Word

def doc_replace_text(source_filename, tokens, values, destination_filename):

    missing = System.Type.Missing
    replaceAll = Word.WdReplace.wdReplaceAll

    word_application = Word.ApplicationClass()
    word_application.visible = False

    document = word_application.Documents.Open(source_filename)

    for i in range(len(tokens)):
        for r in document.StoryRanges:
            #print "i = %d, tokens[i] = %s, values[i] = %s" % (i, tokens[i], values[i])
            r.Find.Text = tokens[i]
            r.Find.Replacement.Text = values[i]
            r.Find.Wrap = Word.WdFindWrap.wdFindContinue
            r.Find.Execute(missing, missing, missing, missing, missing, missing, missing, missing, missing, missing, replaceAll, missing, missing, missing, missing)
            
    time.sleep(3)
    document.SaveAs(destination_filename)
    document.Close()
    document = None

    word_application.Quit()
    word_application = None



def main():
    print("main")

if __name__ == "__main__":
    main()
    currentworkingdirectory = str(os.getcwd()).replace("\\","\\")
    iserror = False
    headervalues = []
    with open(str(currentworkingdirectory)+"\\newusers.csv", 'rb') as csvfile:
        reader = csv.reader(csvfile)
        headersource = reader.next()

    headersource.remove('initial password')
    headersource.remove('userType')

    header = []
    for headerm in headersource:
        header.append("[" + headerm + "]")

    linenumber = 0
    with open(str(currentworkingdirectory)+"\\newusers.csv", 'rb') as csvfile:
        reader = csv.DictReader(csvfile)
        print(header)
        for row in reader:
            notvalidfield = False
            linenumber = linenumber + 1
            for hh in headersource:
                if len(row[hh].strip()) <= 0:
                    notvalidfield = True
            if notvalidfield == True:
                print("line number " + str(linenumber) + " one of field is empty")
            if iserror == False and notvalidfield == False:
                try:
                    for hh in headersource:
                        headervalues.append(row[hh].strip())
                    for hh in headersource:
                        print(hh+":" + row[hh].strip())
                    doc_replace_text(str(currentworkingdirectory)+"\\Application Form.doc", header, headervalues,str(currentworkingdirectory)+"\\Application Form "+row['company'].strip()+".doc")
                    time.sleep(2)
                    headervalues = []
                except:
                    print "Unexpected error:", sys.exc_info()[0]
                    iserror = True

```
