### ISSUE TITLE
import hashlib not working on linux/mono

### ISSUE THREAD

**Issue by gagnus** [IronLanguages/main#1589]
I'm in the process of moving a .NET console application that uses IronPython 2.7.5 to Mono to run on Linux. Moving the code and IronPython DLLs and compiling using xbuild seems to work, however the ironpython cannot find the hashlib import when running through Mono (it works fine on Windows through .NET). Running cpython (2.7) on the same linux box I can definitely import hashlib and running on windows IronPython (the same application code) I can definitely import hashlib.

Any ideas?

**Comment by slide** [comment]
The first release to have any sort of real mono testing is 2.7.7. You probably won't be able to do much on Linux with anything before that.

**Comment by gagnus** [comment]
Thanks - there's no particular reason I'm still at 2.7.5 so will upgrade. Closing this and will reopen if still issues.
