### ISSUE TITLE
MSI Installer ProductVersion 2.7.6 vs 2.7.7

### ISSUE THREAD

**Issue by honekamp** [IronLanguages/main#1620]
The value of property ProductVersion in the MSI of V2.7.6 is set to 2.7.**61003**.0. 
The value of property ProductVersion in the MSI of V2.7.7 is set to 2.7.**7**.1000.

This means that the MSI of V2.7.7 **refuses to install** over an existing installation of 2.7.6, claiming that the **installed version is newer** then the one attempted to install (61003 > 7).

I totally support fixing broken ProductVersions, but this fix means trouble and should have been postponed until a change in the minor version (assuming that it ever) happens.

**Comment by slide** [comment]
There will never be a 2.8 according to Guido, so the decision was made to make this change, fully understanding the issues it might cause.
