### ISSUE TITLE
String formatting of `bool` type

### ISSUE THREAD

**Issue by michaelblyons** [IronLanguages/main#1629]
IronPython 2.7.7rc2

```py
>>> '{}'.format(True) # Want 'True'
'True'
>>> '{:^10}'.format(True) # Want '   True   ', right?
'True'
```

Default Python2 (and maybe Python3?) do not handle this super-well either. They appear to apply `int()` formatting:

```py
>>> '{:^10}'.format(True)
'     1    '
```

All cases can be coerced with `...format(str(True))`, but it's kind of weird to expect padding and receive none.

**Comment by slozier** [comment]
Looks like the format spec is ignored for bool:
https://github.com/IronLanguages/main/blob/827af8c068d823629945ce3bf76febb7a5f79c9b/Languages/IronPython/IronPython/Runtime/Operations/BoolOps.cs#L92

Side note: We should probably match the CPython behavior and display a number when formatting with an alignment.
