### ISSUE TITLE
Support for sys._current_frames

### ISSUE THREAD

**Issue by fabioz** [IronLanguages/main#1630]
Hi IronPython team ;)

I've just updated the PyDev debugger to drop support for older Python versions and it seems I ended up breaking debugging in the current IronPython version because of it...

The issue is that PyDev now requires sys._current_frames to be implemented by the interpreter (available since Python 2.5), but it seems this is not available for IronPython -- this is needed so that the debugger can be faster (i.e.: it runs with untraced frames until some breakpoint is actually added -- at that point it gets the current frames and sets the tracing in them).

So, I'd like to check how feasible it'd be to have this support in IronPython or if there's some workaround to get that info.

Thanks,

Fabio

**Comment by slide** [comment]
If you add -X:Frames to the command line for ipy.exe, does it solve your issue?

**Comment by fabioz** [comment]
No, and neither does adding -X:FullFrames.

**Comment by slide** [comment]
Ok, I see from looking at the code that we don't implement this right now regardless of the -X options. So, this would be a new feature for us to implement.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#41
