### ISSUE TITLE
Repeated hashing doesn't work properly with .NET Core

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1638]
Because of the [different implementation](https://source.dot.net/#System.Security.Cryptography.Algorithms/System/Security/Cryptography/SHA1Managed.cs,5d9dbfaea57ea7b8) of hashing in .NET Core `CloneHasher` doesn't work as expected and doesn't actually create a clone. This causes test failures with repeated hashing.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#30
