### ISSUE TITLE
Add support for facade assemblies

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1640]
.NET Core 2.0 includes facade assemblies (for example System.Xml.dll) which simply contain a bunch of `TypeForwardedTo` attributes pointing to another assembly. These forwarded types are not exposed via reflection and so there is no way to enumerate over the types available in these facade assemblies. For example, the following fails:
```
import clr
clr.AddReference("System.Xml")
import System
dir(System.Xml)
```

Investigate using System.Reflection.MetadataReader as a way to figure out which types are available in the assembly.

https://github.com/dotnet/corefx/issues/19713

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#38
