### ISSUE TITLE
Move IronLanguages/main to IronLanguages/ironpython2?

### ISSUE THREAD

**Issue by slozier** [IronLanguages/main#1655]
As part of #1652 #1653 and #1654 I would suggest forking IronLanguages/main into IronLanguages/ironpython2 where we could:
- rework the file hierarchy into something matching the IronLanguages/ironpython3 repo
- rename the ipy-2.7-maint branch to master (and drop master)

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#29
