### ISSUE TITLE
json module raise error when run with -X:Python30 argument.

### ISSUE THREAD

**Issue by hemnstill** [IronLanguages/main#1658]
I'm trying to update IronPython 2.7.5 → 2.7.7.
When running ipy64.exe with argument -X:Python30 i get an error.

> import json
> ...
> nan, = struct.unpack('>d', b'\x7f\xf8\x00\x00\x00\x00\x00\x00')

IronPython-2.7.7\Lib\json\decoder.py", line 18, in _floatconstants
TypeError: expected str, got bytes

Everything works fine in version 2.7.5 or without -X:Python30 argument in version 2.7.7.
I don't want to remove this argument and modify my existing code.

**Comment by slozier** [comment]
Most likely the json module changed when we updated the stdlib. This should be fixable by adding an overload to the `struct` module.
