### ISSUE TITLE
traceback.format_exc() not working

### ISSUE THREAD

**Issue by Lysander83** [IronLanguages/main#1659]
We have a .net 4 program that hosts IronPython engine. if an exception is raised while running the script then we cannot get the stack trace information by traceback.format_exc()
It worked with IronPython 2.7.5
We cannot reproduce it by running IronPython 2.7 ipy.exe

**Comment by slozier** [comment]
I haven't been able to reproduce. Some more details would be helpful. I tried running the following and it worked fine:
```C#
var test = @"
import traceback
def test():
    raise Exception
try:
    test()
except Exception as e:
    print traceback.format_exc()
";
engine.CreateScriptSourceFromString(test).Execute();
```

**Comment by Lysander83** [comment]
I do not what to say.
I will try to make a simple app to reproduce it next week.
Our IronPython engine uses py files. Maybe it is important.
The traceback and other modules were imported from IP 2.7.7 in both cases the working and not working so the problem must be in IronPython.dll or other dll.

The working version generates the following output:
Traceback (most recent call last):
  File "C:\temp\...\SDTPanel.py", line 158, in _runPanelItemScript
    result=self._panelItemScriptMethod()
  File "<string>", line 50, in VariableUpload
  File "C:\temp\...\SDTTestSetup.py", line 42, in __getitem__
    raise KeyError, "..."
KeyError: "..."

The not working version generates the first 2 lines plus 4 pieces of space character.
Traceback (most recent call last):
  File "C:\temp\...\SDTPanel.py", line 158, in _runPanelItemScript

**Comment by Lysander83** [comment]
Sorry, I have never used github before.
It is still open for me.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#35
