### ISSUE TITLE
Crash when using unquote_plus

### ISSUE THREAD

**Issue by fabioz** [IronLanguages/main#1663]
The following use of unquote_plus crashes IronPython (and makes it impossible to use in PyDev).

"c:\bin\IronPython 2.7.7\ipy.exe" -X:Frames  -X:ExceptionDetail -X:ShowClrExceptions -c "from urllib import unquote_plus; unquote_plus('pydev%5Cplugins%5Corg')"

This worked properly on 2.7.5.

**Comment by slozier** [comment]
This was fixed in #1625.
