### ISSUE TITLE
weakref.ref object sometimes returns None in a mulithreaded scenario

### ISSUE THREAD

**Issue by TI-AviBerko** [IronLanguages/main#1668]
weakref.ref object sometimes returns None in a mulithreades scenario.

I discovered this when using the RPyC library, a NetRef object holds a weakref to it's parent connection, then sometimes the weakref object returns None.
I modified the code a bit to make sure every strong object is perminently stored in a list for the duration of the test and still have the same issue.

(This was recreated with IPy 2.7.4 and 2.7.7, on 2 different PCs)

I managed to recreate the problem with this code:

```Python
import threading
import weakref
import os
from time import sleep


class Test(object):
    def test(self):
        return Test2(weakref.ref(self))

        
class Test2(object):
    def __init__(self, x):
        self._x = x
        

def target(i):
    print i
    t = Test()
    x = t.test()
    sleep(1)

    if x._x() is None:        
        print "x was none"
        os._exit(1)

ths = []
j = 0

while True:
    for i in xrange(20):
        th = threading.Thread(target=target, args=(j + i,))
        th.start()
        ths.append(th)
        
    j += i
    
    for th in ths:
        th.join()
```

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironpython2#210
