### ISSUE TITLE
[ipy 2.7] Exception in SafeConfigParser.readfp() with StringIO

### ISSUE THREAD

**Issue by mbuesch** [IronLanguages/main#196]
SafeConfigParser() throws an exception, if used with io.StringIO.
Versions are CPython 2.7.6 and latest ipy 2.7 from ipy-2.7-maint branch:

> $ cat configtest.py                                                    
> import ConfigParser
> import io
> text = u"[A]\nb=c\n"
> p = ConfigParser.SafeConfigParser()
> p.readfp(io.StringIO(text), "foo")
> $ python2.7 ./configtest.py 
> $ ./ipy ./configtest.py 
> Traceback (most recent call last):
>   File "./configtest.py", line 5, in <module>
> ValueError: write to closed file

**Comment by slide** [comment]
According to https://ironpython.codeplex.com/workitem/34713 this is fixed in 2.7.5 final release. I just tested on latest of ipy-2.7-maint and it does not raise an exception.
