### ISSUE TITLE
IronRuby: Add support of Rational with floating point or real values

### ISSUE THREAD

**Issue by Taritsyn** [IronLanguages/main#215]
The current version of the [`rational18.rb`](https://github.com/IronLanguages/main/blob/master/Languages/Ruby/StdLib/ruby/1.9.1/rational18.rb) does not support of Rational with floating point or real values.

This feature is needed to work with Sass version 3.4.X.

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironruby#8
