### ISSUE TITLE
Unreachable Expression Code Detected

### ISSUE THREAD

**Issue by rinckd** [IronLanguages/main#53]
I'm trying to compile IronPython with Mono Xbuild Version 2.10.8.0

On both Mac and PC (building with Xbuild) I got the same errors.

Runtime/PythonContext.cs(1982,94): error CS0429: Unreachable expression code detected
Runtime/PythonContext.cs(1983,101): error CS0429: Unreachable expression code detected
Runtime/PythonContext.cs(1987,63): error CS0429: Unreachable expression code detected
Task "Csc" execution -- FAILED

This starts a cascade of errors. I don't see this file.

Am I missing something obvious? 
I'm building with: xbuild /p:Configuration=Release Solutions/IronPython.sln

**Comment by slide** [comment]
This doesn't seem to be an issue anymore with more recent Mono versions.
