### ISSUE TITLE
unable to run geninit from linux/mono

### ISSUE THREAD

**Issue by bennidhamma** [IronLanguages/main#75]
Hey guys,

I'm working on adding min_by (I would like to have it for a project.) Forked here, with my crude attempt:

https://github.com/bennidhamma/ironLanguages/commit/4d261233d21a230573552b083237240ee74032f2
https://github.com/bennidhamma/ironLanguages/commit/aa49ac9f3c4ee5042b2a9f1bf8984aedcab47925

but I am unable to run geninit. I tried extracting the batch and cmd file arguments, but I get an error complaining about no output file being specified.

has anyone gotten this to work in Linux/Mono?

thanks!

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironruby#3
