### ISSUE TITLE
bool value conversion malfunctions with Iron python libraries

### ISSUE THREAD

**Issue by sriharshav** [IronLanguages/main#83]
I am finding an issue with iron python libraries while passing a boolean value

Say I have python code "booltest.py" like below.

       if ip_bool is not True and ip_bool is not False :
             print "invalid ip_bool"

And when I call it using Iron Python libraries

     ScriptEngine engine = Python.CreateEngine();
     ScriptScope scope = engine.CreateScope();

     scope.SetVariable("ip_bool", false);
     scope = engine.ExecuteFile("booltest.py", scope);

this results in printing **'invalid ip_bool'** though its value is set to false

Further I updated "booltest.py" to test type and print more info

     print "Before conversion"
     print "class :" + ip_bool.__class__.__name__
     print "value " + str(ip_bool)

     print "ip_bool is not True # " + str(ip_bool is not True)
     print "ip_bool is not False # " + str(ip_bool is not False)

     ip_bool1 = bool(ip_bool)
     print "\nAfter conversion"
     print "class :" + ip_bool1.__class__.__name__
     print "value " + str(ip_bool1)

     print "ip_bool is not True # " + str(ip_bool1 is not True)
     print "ip_bool is not False # " + str(ip_bool1 is not False)

and it yields

+++++++++++++++++++++++
Before conversion
class :bool
value False
ip_bool is not True # True
ip_bool is not False # True

After conversion
class :bool
value False
ip_bool is not True # True
ip_bool is not False # False
+++++++++++++++++++++++

Thus passing a bool value from scripting libraries malfunctions

**Comment by slide** [comment]
This has to do with the fact that True/False are actually objects in IronPython, so when you do an is comparison of a variable with the object True, they are not the same object (when the variable is set from C#). When you set the value from Python, then the True object is assigned to the Python object and thus the instance comparison is True. I'm not sure there is a good fix for this.

See https://github.com/IronLanguages/main/blob/ipy-2.7-maint/Runtime/Microsoft.Dynamic/Runtime/ScriptingRuntimeHelpers.cs#L46

**Comment by jdhardy** [comment]
In @bhadra's example, the call site binder likely converts C# `System.Boolean` into the appropriate Python True/False object, while in @sriharshav's original example `ScriptEngine.SetVariable` has no such conversion.

I see two solutions and a cop-out: adding code in `SetVariable` to convert booleans on the way in (but should we do that to Long as well? Decimal? DateTime? Nullable types?), or adding a special case to `is` handling for Boolean (and possible Nullable types/None, I don't know what it does).

The cop-out is to simply document it, and recommend against using `is` checks on True/False, which is already strongly discouraged by [PEP8](https://www.python.org/dev/peps/pep-0008/#programming-recommendations) (search for "is greeting") anyway.

I don't like special cases in the other code paths so I think we'll leave it as-is.
