### ISSUE TITLE
IronRuby on WinRT

### ISSUE THREAD

**Issue by LonghronShen** [IronLanguages/main#99]
I'm a user of IronRuby. And I'm porting my project to WinRT.
I'm the coordinator of the Runa Engine project which is a XNA and IronRuby based dynamic game engine which fed on the power of IronRuby.
By far I found the problem that the script engine throw an exception that says "Not supporting create new CLR types on this platform."
I think it is because of the missing of reflection on WinRT. Is that possible to port some reflection part of Mono to solve the problem?

**Comment by slide** [comment]
This issue was moved to IronLanguages/ironruby#5
